### PR TITLE
BF16 optimizer for BF16+ZeRO Stage 1

### PR DESCRIPTION
**Pull request by jomayeri**
Directing the engine to use the BF16 optimizer when BF16 and ZeRO stage 1 are enabled.

### CODE REVIEW

**Comment by jomayeri** [comment]
@tjruwase We had discussed before that the BF16 optimizer covers ZeRO stage 1 optimizations. In its current state the engine will route to ZeRO if enabled and ignore that BF16 is also enabled. This corrects that issue. If I had that wrong let me know and I'll just cancel the PR.

**Review by tjruwase — APPROVED** [review]

**Comment by stas00** [comment]
Looks like it broke bf16 training via @SaulLu

```
I launch the same test but on a bf16 training. I'm getting an error when the script tries to get the optimizer:
      File "/gpfswork/rech/cnw/commun/conda/lucile-m4_3/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1207, in _do_optimizer_sanity_check
  File "/gpfswork/rech/cnw/commun/conda/lucile-m4_3/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1207, in _do_optimizer_sanity_check
  File "/gpfswork/rech/cnw/commun/conda/lucile-m4_3/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1207, in _do_optimizer_sanity_check
optimizer_wrapper = self._do_optimizer_sanity_check(basic_optimizer)
  File "/gpfswork/rech/cnw/commun/conda/lucile-m4_3/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1207, in _do_optimizer_sanity_check
    optimizer_wrapper = self._do_optimizer_sanity_check(basic_optimizer)
  File "/gpfswork/rech/cnw/commun/conda/lucile-m4_3/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1207, in _do_optimizer_sanity_check
    optimizer_wrapper = self._do_optimizer_sanity_check(basic_optimizer)
      File "/gpfswork/rech/cnw/commun/conda/lucile-m4_3/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1207, in _do_optimizer_sanity_check
optimizer_wrapper = self._do_optimizer_sanity_check(basic_optimizer)
  File "/gpfswork/rech/cnw/commun/conda/lucile-m4_3/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1207, in _do_optimizer_sanity_check
    raise NotImplementedError(
NotImplementedError: Model data type and gradient accumulation data type must be equal to use ZeRO
```

**Comment by tjruwase** [comment]
@stas00, sorry about that. @jomayeri is already fixing with https://github.com/microsoft/DeepSpeed/pull/2742. 

It would be great your team could test this PR.

**Comment by stas00** [comment]
@SaulLu who discovered this bug will report back in the PR once she gets a chance to test - probably tomorrow as it's very late in Europe.

**Comment by SaulLu** [comment]
Hi @tjruwase, I confirm that the fix proposed in the PR https://github.com/microsoft/DeepSpeed/pull/2742 solved the error! Thank you very much

**Comment by stas00** [comment]
Thank you for validating, Lucile!

**Comment by tjruwase** [comment]
@SaulLu, thanks for the quick confirmation, despite so late on your side. We will merge asap.

**Pull request merged**
