### PR TITLE
Recover shared parameters

### PR DESCRIPTION
**Pull request by ShijieZZZZ**
To address this issue:

[[BUG] DeepSpeed zero_to_fp32.py script ignores some layers while creating FP32 checkpoints from DS ZeRO checkpoints. ](https://github.com/microsoft/DeepSpeed/issues/1896)

Shared parameters that hold reference are missing when extracts fp32 weights from checkpoint. This PR recovers such shared parameters by linking them with their partners.

### CODE REVIEW

**Review by tjruwase — APPROVED** [review]

**Comment by mayank31398** [comment]
Thanks a lot.
Ill try to give this a shot sometime today :)

**Comment by tjruwase** [comment]
@stas00 FYI

**Comment by mayank31398** [comment]
@ShijieZZZZ https://github.com/microsoft/DeepSpeed/pull/3295

**Comment by stas00** [comment]
This code unfortunately doesn't work, since `data_ptr()` always points to `0` in this code, as all compared tensors are of 0 size. And so it re-ties the shared param to whatever first param it encounters. So the recovered checkpoint has invalid shared params.

I think it only happens to work if the first param is the that's shared.

**Comment by stas00** [comment]
in `_zero3_consolidated_16bit_state_dict` we use `ds_id` to identify shared params:

https://github.com/microsoft/DeepSpeed/blob/a094c9763de8d42107cbffd0bb9abb8056aa3c60/deepspeed/runtime/engine.py#L3225-L3228

**Pull request merged**
