### PR TITLE
Update README.md Windows Instructions

### PR DESCRIPTION
**Pull request by erew123**
This is re issue https://github.com/microsoft/DeepSpeed/issues/4729 

This is update to the installation instructions of DeepSpeed on Windows, in an effort to improve them vastly!

Thanks

### CODE REVIEW

**Comment by erew123** [comment]
@microsoft-github-policy-service agree

**Comment by erew123** [comment]
@loadams It failed the formatting check because of a spelling mistake I missed "inot" in step 11. Have corrected that to "into" and re-submitted here. Which I assume is correct and you can re-approve the PR. If I need to create a new PR, please let me know.

Thanks

**Comment by loadams** [comment]
Hi @erew123 - we apologize for the delay in reviewing this.  We've now added support for a Windows whl to be pushed to PyPI and will be doing so with our next release.  So I'll close this PR for now and we can add some of these directions as needed.

**Comment by erew123** [comment]
Hi @loadams That's great news to hear! Thanks for looking into this and Im sure it will be a great thing for the community. All the best.

**Pull request closed without merging**
