### PR TITLE
fix #2240: wrong time unit in flops_profiler

### LINKED ISSUE #2240: [BUG] Wrong time unit in flops profiler
**Describe the bug**
The elapsed time in `flops_profiler` gets by `_get_elapsed_msec` is msec now, introducing many time unit inconsistencies. #2090 and its fix #2095, and #1934 have resolved some of the misuses. 

I mainly examined the MoE part and found the remaining below. 

1. The flop profiler log print the duration as ms
https://github.com/microsoft/DeepSpeed/blob/fda63432ba67643d2f54885e45f0b2058fa2b937/deepspeed/runtime/engine.py#L1714-L1716
However it is captured and *1000 manually
https://github.com/microsoft/DeepSpeed/blob/fda63432ba67643d2f54885e45f0b2058fa2b937/deepspeed/moe/sharded_moe.py#L434

2. The time breakdown log needs ms here
https://github.com/microsoft/DeepSpeed/blob/fda63432ba67643d2f54885e45f0b2058fa2b937/deepspeed/runtime/engine.py#L2095-L2097

Similar issues: #2090 #1934

### PR DESCRIPTION
**Pull request by yzs981130**
Fix #2240

### CODE REVIEW

**Review by cli99 — APPROVED** [review]

**Comment by tjruwase** [comment]
@yzs981130, thanks for the PR. Please see below for formatting instructions: 
https://github.com/microsoft/DeepSpeed/blob/master/CONTRIBUTING.md#prerequisites

**Comment by yzs981130** [comment]
> formatting instructions

Thanks for the information! I will update the pr soon.

**Comment by yzs981130** [comment]
hi @tjruwase , is there anything wrong with the [failed unit-tests](https://github.com/microsoft/DeepSpeed/runs/7952194071?check_suite_focus=true)? I am not authorized to see the full log. Thanks!

**Comment by tjruwase** [comment]
> hi @tjruwase , is there anything wrong with the [failed unit-tests](https://github.com/microsoft/DeepSpeed/runs/7952194071?check_suite_focus=true)? I am not authorized to see the full log. Thanks!

This is because our CI system is having problems at the moment. I will restart the unit tests. Sorry for the inconvenience.

**Pull request merged**
