### PR TITLE
Fix error in get_model_profile when output_file argument is a relative path without a prefix

### PR DESCRIPTION
**Pull request by bstee615**
When I gave an `output_file` argument such as "profile.txt" without a prefix to `get_model_profile`, it errors out when it tries to ensure that the directory containing `output_file` exists.

Here is the code I used to reproduce it (the example in the tutorial):
```python
#%%
import torch
from transformers import BertForSequenceClassification, BertTokenizer
from deepspeed.profiling.flops_profiler import get_model_profile


def bert_input_constructor(batch_size, seq_len, tokenizer):
    fake_seq = ""
    for _ in range(seq_len - 2):  # ignore the two special tokens [CLS] and [SEP]
      fake_seq += tokenizer.pad_token
    inputs = tokenizer([fake_seq] * batch_size,
                       padding=True,
                       truncation=True,
                       return_tensors="pt")
    labels = torch.tensor([1] * batch_size)
    inputs = dict(inputs)
    inputs.update({"labels": labels})
    return inputs


with torch.cuda.device(0):
    tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
    model = BertForSequenceClassification.from_pretrained('bert-base-uncased')
    batch_size = 4
    seq_len = 128
    enable_profile = True
    if enable_profile:
      flops, macs, params = get_model_profile(
          model,
          kwargs=bert_input_constructor(batch_size, seq_len, tokenizer),
          print_profile=True,
          detailed=True,
          output_file="profile.txt",
      )
    else:
      inputs = bert_input_constructor((batch_size, seq_len), tokenizer)
      outputs = model(inputs)
```

Failing log from before the fix:
```
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "mytest.py", line 28, in <module>
    flops, macs, params = get_model_profile(
  File "/home/benjis/code/DeepSpeed-bugfix/deepspeed/profiling/flops_profiler/profiler.py", line 1212, in get_model_profile
    prof.print_model_profile(profile_step=warm_up,
  File "/home/benjis/code/DeepSpeed-bugfix/deepspeed/profiling/flops_profiler/profiler.py", line 259, in print_model_profile
    os.makedirs(dir_path)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''
```

Successful log from after the fix:
```
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.bias', 'cls.predictions.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.decoder.weight']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
```

### CODE REVIEW

**Comment by bstee615** [comment]
By the way, could you add the `hacktoberfest-accepted` label if this PR is accepted so I can get credit for hacktoberfest? :smile:

**Review by cli99 — APPROVED** [review]

**Comment by bstee615** [comment]
@jeffra could you please change it to `hacktoberfest-accepted`? I think this exact spelling is required. Thank you for adding the label. Sorry for the bother

**Comment by bstee615** [comment]
@cli99 Looks like merging is restricted to authorized users. Can you merge this PR when you have a chance?

**Comment by bstee615** [comment]
Looks like this PR was subsumed by #2395. Should I close it out? I get 2 emails per day notifying me that the tests have timed out.

**Pull request closed without merging**
