### PR TITLE
skip torch.zeros and tensor.copy_ when model parallel is not used

### PR DESCRIPTION
**Pull request by guoyejun**

### CODE REVIEW

**Review by tjruwase — APPROVED** [review]

**Comment by guoyejun** [comment]
any other comment? thanks.

**Comment by tjruwase** [comment]
@guoyejun, no comments, as the PR looks good and is already approved :). 

Just a small optional request, could you add some numbers on the perf impact of this fix? 

Will merge asap. Thanks!

**Comment by guoyejun** [comment]
@tjruwase  thanks.

I saw ~5% performance gain after clear all the distribution operations for mp size 1 with 4 changes, https://github.com/microsoft/DeepSpeed/pull/2454 is the first change, will create PRs for other changes one by one.

As for this PR for mp_group none, I got the idea from code review, and did not get a perf test since my case is mp size 1.

**Comment by guoyejun** [comment]
> @tjruwase thanks.
> 
> I saw ~5% performance gain after clear all the distribution operations for mp size 1 with 4 changes, #2454 is the first change, will create PRs for other changes one by one.
> 
> As for this PR for mp_group none, I got the idea from code review, and did not get a perf test since my case is mp size 1.

Hi, 2 PRs have been merged, #2454 and #2494, the other two changes happen in Megatron-DeepSpeed, just found that my code base is a bit old in DeepSpeedExamples, I'm unable to verify the changes based on Megatron-DeepSpeed, so the changes will be pending.

actually, most of the gain is contributed by #2454 and #2494.

**Comment by guoyejun** [comment]
hi, anything else needed before the merge? thanks.

**Comment by tjruwase** [comment]
> hi, anything else needed before the merge? thanks.

No, should merge soon. Sorry for the delay.

**Comment by guoyejun** [comment]
hi, just a kind reminder, thanks.

**Pull request merged**
