### PR TITLE
HPUAccelerator: remove support in set_visible_devices_envs

### PR DESCRIPTION
**Pull request by nelyahu**
The way deepspeed sets it is not correct with all HPU instances and may lead to incorrect behavior.

### CODE REVIEW

**Comment by delock** [comment]
Hi @nelyahu in the link https://docs.habana.ai/en/latest/PyTorch/Reference/PT_Multiple_Tenants_on_HPU/Multiple_Workloads_Single_Docker.html specificed in the code.  It mentioned `HABANA_VISIBLE_MODULES` is used for multi-tenant on HPU, how does this usage conflict with `set_visible_devices_envs()` in DeepSpeed?  Thanks!

**Comment by nelyahu** [comment]
@delock on Intel Gaudi accelerator (HPU), the visible module ids are determines by the `hl-smi -L ` command, it does not always 0,1,2,3,4,5,6,7 and specially when running multiple VMs on the same server each VM can get different module
For example, the case of 2 VMs 
VM#1 can get module ids 1,4,5,2
VM#2 can get 7,0,3,6

**Comment by delock** [comment]
Hi @nelyahu From the title and description this PR intends to avoid set_visible_devices_envs on this line: https://github.com/microsoft/DeepSpeed/blob/ffe0af23575c4f03a07408eacfc50b1a58781429/deepspeed/launcher/launch.py#L166

This PR also nullify this line which does not set_visible_devices_envs, is it also intended?
https://github.com/microsoft/DeepSpeed/blob/ffe0af23575c4f03a07408eacfc50b1a58781429/deepspeed/launcher/runner.py#L408


> @delock on Intel Gaudi accelerator (HPU), the visible module ids are determines by the `hl-smi -L ` command, it does not always 0,1,2,3,4,5,6,7 and specially when running multiple VMs on the same server each VM can get different module For example, the case of 2 VMs VM#1 can get module ids 1,4,5,2 VM#2 can get 7,0,3,6

**Comment by delock** [comment]
Hi @nelyahu, the latest push added cosmetic change from other 8 files which is unrelated.

**Comment by nelyahu** [comment]
> Hi @nelyahu, the latest push added cosmetic change from other 8 files which is unrelated.

Yes, formatter version issue. fixed

**Review by loadams — APPROVED** [review]

**Pull request merged**
