### PR TITLE
call empty_cache to really free up GPU memory as described in comment

### PR DESCRIPTION
**Pull request by guoyejun**

### CODE REVIEW

**Comment by guoyejun** [comment]
see more detail at https://pytorch.org/docs/stable/notes/cuda.html#cuda-memory-management, thanks

Calling [empty_cache()](https://pytorch.org/docs/stable/generated/torch.cuda.empty_cache.html#torch.cuda.empty_cache) releases all unused cached memory from PyTorch so that those can be used by other GPU applications.

**Comment by tjruwase** [comment]
@guoyejun, thanks for this PR. However, I don't think this is needed since the GPU memory will be reused immediately. In this case, the reason for moving tensors to CPU is so that they can be concatenated and read back into GPU memory. So, it is not to actually free up GPU memory. See below: 

https://github.com/microsoft/DeepSpeed/blob/7e2103f8e2c9a4e1be6c3aaa7929f765eb5dd7a4/deepspeed/runtime/zero/stage_1_and_2.py#L316-L324

**Comment by guoyejun** [comment]
the reason is that the gpu memory could not be reused due to the memory management in pytorch.

suppose we have a model with 10GB parameters, when it is moved to GPU, the parameters are moved to GPU memory one by one, and so pytorch will allocate GPU memory one by one (maybe hundreds of MB for each allocation).  

when we move the tensors to CPU, and yes, the allocated 10GB are returned back to pytorch, but they are still allocated from driver perspective, and so we'll see "MA 0GB, CA 10GB" with see_memory_usage().

Then, we flat the tensors and ask for 10GB device memory in one allocation, the previous 10GB device memory could not be used for this allocation due to the memory management in pytorch, and so another continuous 10GB will be allocated, and now we'll see "MA 10GB, CA 20GB" with see_memory_usage, (the previous 10GB may or may not be reused in the future).

with this PR, we'll see "MA 10GB, CA 10GB" with see_memory_usage after the tensor flat, it helps the memory management in pytorch.

**Comment by tjruwase** [comment]
@guoyejun, thanks for your explanation. In our experience, pytorch GC has done a good job of defragmenting/reusing cached memory so that we have not previously seen this kind of issue. However, it is possible that something has changed/broken with pytorch GC that is making you see that problem. For help future investigation, can you please share the following with this PR: 
1.  Pytorch version, 
2.  Model size,
3. Before and after `see_memory_usage()` log printouts

Thanks!

**Comment by guoyejun** [comment]
Pytorch version:
1.12.1, installed with command at https://pytorch.org/get-started/previous-versions/.  
We also tried to build pytorch 1.13 from source, the same issue.

Model size:
~3.6B parameters with bf16 (and so ~7.2B bytes), it is built on GPT2 with 30 layers, 3072 hidden size, 32 heads, seq-length 2048, and with batch size 8.

Before and after see_memory_usage() log printouts:

without this PR:
```
[2022-12-14 23:45:14,316] [INFO] [utils.py:821:see_memory_usage] DeepSpeed Engine: After args sanity test
[2022-12-14 23:45:14,316] [INFO] [utils.py:822:see_memory_usage] MA 6.63 GB         Max_MA 6.63 GB         CA 6.63 GB         Max_CA 7 GB 
[2022-12-14 23:45:14,316] [INFO] [utils.py:830:see_memory_usage] CPU Virtual Memory:  used = 30.64 GB, percent = 3.0%
[2022-12-14 23:45:14,367] [INFO] [utils.py:821:see_memory_usage] DeepSpeed Engine: Before configure distributed model
[2022-12-14 23:45:14,368] [INFO] [utils.py:822:see_memory_usage] MA 6.63 GB         Max_MA 6.63 GB         CA 6.63 GB         Max_CA 7 GB 
[2022-12-14 23:45:14,368] [INFO] [utils.py:830:see_memory_usage] CPU Virtual Memory:  used = 30.66 GB, percent = 3.0%
[2022-12-14 23:45:14,386] [INFO] [logging.py:68:log_dist] [Rank 0] DeepSpeed Flops Profiler Enabled: True
[2022-12-14 23:45:14,386] [INFO] [logging.py:68:log_dist] [Rank 0] Removing param_group that has no 'params' in the client Optimizer
[2022-12-14 23:45:14,387] [INFO] [logging.py:68:log_dist] [Rank 0] Using client Optimizer as basic optimizer
[2022-12-14 23:45:14,405] [INFO] [logging.py:68:log_dist] [Rank 0] DeepSpeed Basic Optimizer = Adam
[2022-12-14 23:45:14,405] [INFO] [utils.py:53:is_zero_supported_optimizer] Checking ZeRO support for optimizer=Adam type=<class 'torch.optim.adam.Adam'>
[2022-12-14 23:45:14,405] [INFO] [logging.py:68:log_dist] [Rank 0] Creating fp16 ZeRO stage 2 optimizer
[2022-12-14 23:45:14,405] [INFO] [stage_1_and_2.py:143:__init__] Reduce bucket size 500,000,000
[2022-12-14 23:45:14,405] [INFO] [stage_1_and_2.py:144:__init__] Allgather bucket size 500,000,000
[2022-12-14 23:45:14,405] [INFO] [stage_1_and_2.py:145:__init__] CPU Offload: False
[2022-12-14 23:45:14,405] [INFO] [stage_1_and_2.py:146:__init__] Round robin gradient partitioning: False
...
Rank: 0 partition count [8, 8] and sizes[(444776448, False), (150528, False)] 
[2022-12-14 23:45:30,556] [INFO] [utils.py:821:see_memory_usage] Before initializing optimizer states
[2022-12-14 23:45:30,557] [INFO] [utils.py:822:see_memory_usage] MA 8.29 GB         Max_MA 9.12 GB         CA 15.75 GB         Max_CA 16 GB 
```

with this PR:
```
[2022-12-15 03:45:35,185] [INFO] [utils.py:821:see_memory_usage] DeepSpeed Engine: After args sanity test
[2022-12-15 03:45:35,185] [INFO] [utils.py:822:see_memory_usage] MA 6.63 GB         Max_MA 6.63 GB         CA 6.63 GB         Max_CA 7 GB 
[2022-12-15 03:45:35,186] [INFO] [utils.py:830:see_memory_usage] CPU Virtual Memory:  used = 30.28 GB, percent = 3.0%
[2022-12-15 03:45:35,235] [INFO] [utils.py:821:see_memory_usage] DeepSpeed Engine: Before configure distributed model
[2022-12-15 03:45:35,236] [INFO] [utils.py:822:see_memory_usage] MA 6.63 GB         Max_MA 6.63 GB         CA 6.63 GB         Max_CA 7 GB 
[2022-12-15 03:45:35,236] [INFO] [utils.py:830:see_memory_usage] CPU Virtual Memory:  used = 30.3 GB, percent = 3.0%
[2022-12-15 03:45:35,255] [INFO] [logging.py:68:log_dist] [Rank 0] DeepSpeed Flops Profiler Enabled: True
[2022-12-15 03:45:35,255] [INFO] [logging.py:68:log_dist] [Rank 0] Removing param_group that has no 'params' in the client Optimizer
[2022-12-15 03:45:35,255] [INFO] [logging.py:68:log_dist] [Rank 0] Using client Optimizer as basic optimizer
[2022-12-15 03:45:35,274] [INFO] [logging.py:68:log_dist] [Rank 0] DeepSpeed Basic Optimizer = Adam
[2022-12-15 03:45:35,274] [INFO] [utils.py:53:is_zero_supported_optimizer] Checking ZeRO support for optimizer=Adam type=<class 'torch.optim.adam.Adam'>
[2022-12-15 03:45:35,274] [INFO] [logging.py:68:log_dist] [Rank 0] Creating fp16 ZeRO stage 2 optimizer
[2022-12-15 03:45:35,274] [INFO] [stage_1_and_2.py:143:__init__] Reduce bucket size 500,000,000
[2022-12-15 03:45:35,274] [INFO] [stage_1_and_2.py:144:__init__] Allgather bucket size 500,000,000
[2022-12-15 03:45:35,274] [INFO] [stage_1_and_2.py:145:__init__] CPU Offload: False
[2022-12-15 03:45:35,274] [INFO] [stage_1_and_2.py:146:__init__] Round robin gradient partitioning: False
...
Rank: 0 partition count [8, 8] and sizes[(444776448, False), (150528, False)] 
[2022-12-15 03:45:47,946] [INFO] [utils.py:821:see_memory_usage] Before initializing optimizer states
[2022-12-15 03:45:47,947] [INFO] [utils.py:822:see_memory_usage] MA 8.29 GB         Max_MA 9.12 GB         CA 8.31 GB         Max_CA 9 GB 
[2022-12-15 03:45:47,947] [INFO] [utils.py:830:see_memory_usage] CPU Virtual Memory:  used = 34.5 GB, percent = 3.4%
```

**Comment by tjruwase** [comment]
@guoyejun, great thanks for sharing these details. LGTM!

**Review by tjruwase — APPROVED** [review]

**Pull request merged**
