### PR TITLE
move is_checkpointable call reducing torch.compile Graph breaks

### PR DESCRIPTION
**Pull request by NirSonnenschein**
We have encountered a performance issue when running torch compile on a model utilizing
the pipeline engine (Mixtral). 
The issue was found to be the is_checkpointable function which is called in the engine's forward function.
This function creates a graph break when using torch.compile leading to decreased performance (particularly since this happens in every forward call). We propose a change in the way is_checkpointable is checked by precomputing and storing its value before the forward call and accessing the stored values in the forward function.
given this change the graph break in the forward call is avoided which should lead to better performance for torch compile.

### CODE REVIEW

**Comment by NirSonnenschein** [comment]
Hi @duli2012, 
when you have a moment would it be possible to review this change.
thanks

**Comment by tjruwase** [comment]
> Hi @duli2012, when you have a moment would it be possible to review this change. thanks

@tohtana, will help review.

**Comment by NirSonnenschein** [comment]
Hi @tohtana,
when you have a moment would it be possible to review this change. 
thanks

**Review by tohtana — APPROVED** [review]

**Comment by tohtana** [comment]
@NirSonnenschein This is a great improvement. Sorry for the delay. I just approved.

**Comment by loadams** [comment]
The current test failures will be resolved after https://github.com/microsoft/DeepSpeed/pull/5797 completes.

**Comment by NirSonnenschein** [comment]
Thanks @tohtana and @loadams

**Pull request merged**
