### PR TITLE
Fix checkpoint conversion when model layers share weights

### LINKED ISSUE #3824: [BUG] Unable to reconstruct full weights from ZeRO-2 checkpoint when layers share weights
**Describe the bug**
There is an edge case in which a ZeRO-2 checkpoint is missing weights after running it through the `deepspeed.utils.zero_to_fp32.get_fp32_state_dict_from_zero_checkpoint` utility function. Layers that share weights can't be recovered, leading to a missing keys error when calling `model.load_state_dict()`.

**To Reproduce**
Save the below script into a file `repro.py`.
```py
import os
import argparse
import torch
import torch.nn as nn

import deepspeed
from deepspeed.utils.zero_to_fp32 import get_fp32_state_dict_from_zero_checkpoint


class ModelWithSharedWeights(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer0 = nn.Linear(100, 100)
        self.layer1 = nn.Linear(200, 200)
        self.layer2 = nn.Linear(300, 300)
        # tie layer 1 and layer 2
        self.layer1.weight = self.layer2.weight


config = {
    "train_micro_batch_size_per_gpu": 2,
    "zero_allow_untested_optimizer": True,
    "zero_optimization": {"stage": 2},
}


rank = int(os.environ["LOCAL_RANK"])

torch.cuda.set_device(rank)
model = ModelWithSharedWeights()
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

deepspeed_engine, _, _, _ = deepspeed.initialize(
    args=argparse.Namespace(device_rank=rank),
    config=config,
    model=model,
    optimizer=optimizer,
)
deepspeed_engine.save_checkpoint("checkpoints_ds/checkpoint0.pt", tag="checkpoint")

if rank == 0:
    model = ModelWithSharedWeights()
    state_dict = get_fp32_state_dict_from_zero_checkpoint("checkpoints_ds/checkpoint0.pt", tag="checkpoint")

    # Fails with
    # RuntimeError: Error(s) in loading state_dict for ModelWithSharedWeights:
    # Missing key(s) in state_dict: "layer2.weight".
    model.load_state_dict(state_dict)

torch.distributed.barrier()

```
Run this command:
```bash
torchrun --nproc_per_node 2 repro.py
```
Error:
```
Traceback (most recent call last):
  File "/home/adrian/repositories/lightning/repro_ds.py", line 52, in <module>
    model.load_state_dict(state_dict)
  File "/home/adrian/.conda/envs/lightning/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2056, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ModelWithSharedWeights:
        Missing key(s) in state_dict: "layer2.weight". 
```

**Expected behavior**
The model should load the weights without error.

**ds_report output**

```
Setting ds_accelerator to cuda (auto detect)
Setting ds_accelerator to cuda (auto detect)
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
async_io ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.1
 [WARNING]  using untested triton version (2.1.0+7d1a95b046), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
utils .................. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/home/adrian/.conda/envs/lightning/lib/python3.10/site-packages/torch']
torch version .................... 2.1.0.dev20230529+cu118
deepspeed install path ........... ['/home/adrian/repositories/DeepSpeed/deepspeed']
deepspeed info ................... 0.9.4+f483c034, f483c034, master
torch cuda version ............... 11.8
torch hip version ................ None
nvcc version ..................... 12.1
deepspeed wheel compiled w. ...... torch 2.1, cuda 11.8
```

**System info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04] Ubuntu 18.04
 - GPU count and types [e.g. two machines with x8 A100s each] 8x A100
 - Interconnects (if applicable) [e.g., two machines connected with 100 Gbps IB]
 - Python version 3.10
 - Any other relevant info about your setup

**Launcher context**
See command above, it is using torchrun. 

**Docker context**
N/A

**Additional context**

Originally reported in Lightning: https://github.com/Lightning-AI/lightning/issues/15694

### PR DESCRIPTION
**Pull request by awaelchli**
Fixes #3824

The added test case fails on master.

### CODE REVIEW

**Comment by awaelchli** [comment]
@microsoft-github-policy-service agree

**Comment by awaelchli** [comment]
Hey DeepSpeed team @tjruwase @ShijieZZZZ @jeffra, could you take a look at my bugfix here? I appreciate the feedback.

**Comment by awaelchli** [comment]
I would really appreciate it if I could get some feedback on the changes. We have several users who reported seeing this problem in Lightning (https://github.com/Lightning-AI/lightning/issues/16277, https://github.com/Lightning-AI/lightning/issues/15694).

Even if the answer is no, I'd like to know. I would really prefer to have the fix in DeepSpeed, because if this PR can't be merged, we would have to patch the DeepSpeedEngine method from within Lightning. This would add additional maintenance effort for us as to keep the code updated, and then the issue would still be there for regular deepspeed users.

**Review by tjruwase — APPROVED** [review]

**Comment by tjruwase** [comment]
@awaelchli, apologies for the delay. PR looks good.

**Comment by awaelchli** [comment]
Amazing, thanks for taking another look!

**Pull request merged**
