### PR TITLE
[NPU]Add ZeRO-Infinity feature for NPU

### PR DESCRIPTION
**Pull request by misstek**
Add ZeRO-Infinity feature for NPU devices. 
I add a new `async_io.py` in `op_builder/npu` and compilation preprocessing judgment in `deepspeed_aio_thread.cpp` specifically for NPU, which will be isolated from other devices such as the GPU and will not affect each other.
See what we have already done in https://github.com/microsoft/DeepSpeed/issues/4567 .

### CODE REVIEW

**Comment by misstek** [comment]
Hi @cmikeh2 @awan-10 @arashb , would you please help me launch CI and review this PR.  Thank you.

**Comment by misstek** [comment]
Hi @tjruwase , thanks for your help launching CI and I have fixed the formatting failure issue. But the failure of `nv-transformers-v100` unit test does not seem to be caused by the code I committed.

**Comment by misstek** [comment]
Hi @tjruwase , would you please help me launch unit-tests again? Thank you.

**Comment by tjruwase** [comment]
@misstek, can you please fix the formatting issues? https://github.com/microsoft/DeepSpeed/blob/master/CONTRIBUTING.md#contributing

**Comment by misstek** [comment]
> @misstek, can you please fix the formatting issues? https://github.com/microsoft/DeepSpeed/blob/master/CONTRIBUTING.md#contributing

Hi, @tjruwase , the formatting failure has been fixed according to `CONTRIBUTING.md`. Please launch formatting check again, sorry for the inconvenience and thank you.

```
pre-commit run --files csrc/aio/py_lib/deepspeed_aio_thread.cpp op_builder/npu/__init__.py op_builder/npu/async_io.py
Check hooks apply to the repository..................(no files to check)Skipped
Check for useless excludes...........................(no files to check)Skipped
Check for case conflicts.................................................Passed
Check JSON...........................................(no files to check)Skipped
Check for broken symlinks............................(no files to check)Skipped
Check Yaml...........................................(no files to check)Skipped
Detect Destroyed Symlinks................................................Passed
Fix End of Files.........................................................Passed
fix UTF-8 byte order marker..............................................Passed
Fix python encoding pragma...............................................Passed
Mixed line ending........................................................Passed
Fix requirements.txt.................................(no files to check)Skipped
Trim Trailing Whitespace.................................................Passed
yapf.....................................................................Passed
clang-format.............................................................Passed
check-torchdist..........................................................Passed
check-license............................................................Passed
codespell................................................................Passed
flake8...................................................................Passed
check-torchcuda..........................................................Passed

```

**Comment by misstek** [comment]
Hi @mrwyattii @jomayeri , since this pull request has passed all tests, could you please review it and add it to merge queue. Thank you.

**Review by tjruwase — APPROVED** [review]

**Comment by misstek** [comment]
Hi @tjruwase , I noticed that this PR has been approved. Is it ready to be put into the merge queue? Thank you.

**Pull request merged**
