### PR TITLE
Switch from HIP_PLATFORM_HCC to HIP_PLATFORM_AMD

### PR DESCRIPTION
**Pull request by loadams**
This appears to have been deprecated a while ago.  AMD docs [here](https://cgmb-rocm-docs.readthedocs.io/en/latest/Current_Release_Notes/Deprecation.html#changed-hip-environment-variables-in-rocm-v4-1-release) and [here](https://rocm.docs.amd.com/projects/HIP/en/latest/user_guide/hip_porting_guide.html#identifying-hip-target-platform).

### CODE REVIEW

**Comment by loadams** [comment]
@jithunnair-amd if you could review this to make sure I'm implementing this correctly, since I believe this is deprecated: https://rocm.docs.amd.com/projects/HIP/en/latest/user_guide/hip_porting_guide.html#identifying-hip-target-platform

**Comment by loadams** [comment]
Need to wait for the additional one added in #4538.

**Review by mrwyattii — APPROVED** [review]

**Comment by mrwyattii** [comment]
Looks like this was added in ROCM 4.1 release (which is 2+ years old). So we shouldn't run into any issues with backwards compatibility, right? I presume most if not all AMD users are on ROCM4.1+

**Comment by loadams** [comment]
> Looks like this was added in ROCM 4.1 release (which is 2+ years old). So we shouldn't run into any issues with backwards compatibility, right? I presume most if not all AMD users are on ROCM4.1+

That's what it looks like to me, and it will be fully deprecated in ROCm 6+ coming later this year, it also looks like that means maybe only the MI25s would be impacted?  So I think we should be fine.

**Pull request merged**
