### PR TITLE
use `Flops Profiler` to test `model.generate()`

### PR DESCRIPTION
**Pull request by CaffreyR**
Fix issue #2514 

Nowadays, the `Flops Profiler` can test `forward` for transformers such as `bert`, but for `t5`, it actually uses `model.generate()` during inference. So how to use Flops Profiler to test `model.generate()` ?

### CODE REVIEW

**Comment by CaffreyR** [comment]
> 

@microsoft-github-policy-service agree

**Comment by tjruwase** [comment]
@CaffreyR, thanks for the PR. Can you please remove the binary files? Thanks!

**Comment by CaffreyR** [comment]
Hi @tjruwase , do you mean the `.DS_Store`?

**Comment by jeffra** [comment]
@cli99 can you review this PR?

**Review by cli99 — APPROVED** [review]

**Pull request merged**
