### PR TITLE
Fix op_builder against PyTorch nightly

### PR DESCRIPTION
**Pull request by malfet**
After https://github.com/pytorch/pytorch/pull/100557 PyTorch is free to use C++17 feature in it's headers, such as `std::optional`, `if constexpr` etc.

This update language standard for DS extensions to use C++17 standard by default

### CODE REVIEW

**Comment by stas00** [comment]
For context please see the breakage reported when trying to build deepspeed with pt-nightly as of last week:
https://github.com/pytorch/pytorch/issues/102082

**Comment by stas00** [comment]
@malfet, will your changes work with older pytorch versions? if I'm not mistaken deepspeed needs to work with pt-1.9 or higher.

**Comment by malfet** [comment]
> @malfet, would your proposed changes work with older pytorch versions? if I'm not mistaken deepspeed needs to work with pt-1.9 or higher.

@stas00 I have not checked with pt-1.9, but I don't see why not (it should clearly work with 1.13/2.0), as C++17 is backward compatible with C++14. It might print a few warnings (for example because older PyTorch builds use [`std::iterator`](https://en.cppreference.com/w/cpp/iterator/iterator)

**Comment by stas00** [comment]
@jeffra

**Comment by malfet** [comment]
Looking into formatting failure, but will not push a change until other signals have finished.

**Review by cmikeh2 — APPROVED** [review]

**Review by jeffra — APPROVED** [review]
Thank you @malfet! 🚀

**Comment by fecet** [comment]
Still cannot build, could you please provide the command and environment while building?

**Comment by dainey94** [comment]
yes sir !! Thanks Sir

Tải xuống Outlook dành cho Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request merged**
