### PR TITLE
Use py-cpuinfo to detect SIMD_WIDTH in platform-independent way

### PR DESCRIPTION
**Pull request by lostmsu**
This enables AVX2 and AVX512 detection on Windows.

### CODE REVIEW

**Review by RezaYazdaniAminabadi — APPROVED** [review]

**Comment by RezaYazdaniAminabadi** [comment]
Thanks @lostmsu for the PR 👍 I have tried this on AMD and Intel CPUs and both passed the unit.

**Comment by lostmsu** [comment]
How do I correct formatting?

**Comment by jeffra** [comment]
> How do I correct formatting?

Can you run our `pre-commit` formatter? See our contributor guide here: https://github.com/microsoft/DeepSpeed/blob/master/CONTRIBUTING.md

**Comment by lostmsu** [comment]
@jeffra you might want to make the formatting check run without requiring approval.

**Review by jeffra — APPROVED** [review]
Thank you for the contribution @lostmsu!

**Comment by lostmsu** [comment]
@jeffra do I need to look into the test failures?

**Comment by lostmsu** [comment]
@RezaYazdaniAminabadi @jeffra I have another commit built on top of this one to support CPU Adam and Adagrad on Windows: https://github.com/lostmsu/DeepSpeed/commit/4daa425648b69d2ca20a8a7a989d1e0642c469d6

Just nagging here to get this in so I could publish another PR )

**Comment by jeffra** [comment]
> @jeffra do I need to look into the test failures?

We were seeing very strange test runner failures all day yesterday, for some reason tests would be marked Abandoned after 15min or running. We've been debugging and testing to see if we could resolve the issue but today it is "magically" working again, it might have been an intermittent github actions server-side issue. If tests pass now then we can merge this today.

**Pull request merged**
