### PR TITLE
fix ZERO_OPTIMIZATION_REDUCE_SCATTER_DEFAULT default value 

### PR DESCRIPTION
**Pull request by mpjlu**
There is more than 20% performance improvement when set ZERO_OPTIMIZATION_REDUCE_SCATTER_DEFAULT = true.

The default value in the docs is also true. 
https://www.deepspeed.ai/docs/config-json/#zero-optimizations-for-fp16-training
image

Most people will not set reduce_scatter in the config file,  to avoid the performance issue, we propose to do this change.

### CODE REVIEW

**Comment by mpjlu** [comment]
@tjruwase

**Comment by e-sha** [comment]
There is an open issue with reduce-scatter and ZeRO stage 1
https://github.com/microsoft/DeepSpeed/issues/967

**Comment by mpjlu** [comment]
> There is an open issue with reduce-scatter and ZeRO stage 1
> #967
reduce-scatter not only used for stage 1, but also stage 2. And the current stage 1 implementation will be deprecated, so we propose to revert   ZERO_OPTIMIZATION_REDUCE_SCATTER_DEFAULT default value to true.

**Comment by mpjlu** [comment]
> #1042 should fix the perf and correctness issues in zero stage 1. It will be merged early this week. Feel free to give it an early try though. Hopefully you see better performance :)

Yes, I think the perf and correctness issues in zero stage 1 will be fixed. Will we revert ZERO_OPTIMIZATION_REDUCE_SCATTER_DEFAULT default value to true?

**Comment by jeffra** [comment]
> > #1042 should fix the perf and correctness issues in zero stage 1. It will be merged early this week. Feel free to give it an early try though. Hopefully you see better performance :)
> 
> Yes, I think the perf and correctness issues in zero stage 1 will be fixed. Will we revert ZERO_OPTIMIZATION_REDUCE_SCATTER_DEFAULT default value to true?

I’ll double check tomorrow but I believe the new PR does this.

**Review by mpjlu — COMMENTED** [review]
no newline at end of file

**Review by jeffra — APPROVED** [review]

**Pull request merged**
