### PR TITLE
Control ZeRO wall clock timers

### PR DESCRIPTION
**Pull request by tjruwase**
Ensure ZeRO 2&3 wall clock timers are controlled from deepspeed config.

### CODE REVIEW

**Comment by stas00** [comment]
This fixed zero2, thank you!

zero3 still still prints for each step:

```
[2021-03-10 15:27:46,893] [INFO] [utils.py:555:see_memory_usage] After zero_optimizer step
[2021-03-10 15:27:46,894] [INFO] [utils.py:556:see_memory_usage] MA 0.06 GB         Max_MA 0.26 GB         CA 0.71 GB         Max_CA 1 GB
[2021-03-10 15:27:46,895] [INFO] [utils.py:564:see_memory_usage] CPU Virtual Memory:  used = 62.62 GB, percent = 49.8%
```

**Comment by stas00** [comment]
after your last commit other debug prints replaced the old ones, now I get these for each step:

```
[2021-03-10 18:22:31,608] [INFO] [logging.py:60:log_dist] [Rank 0] step=25, skipped=5, lr=[1.446140557591026e-05], mom=[[0.8, 0.999]]
[2021-03-10 18:22:31,608] [INFO] [timer.py:154:stop] 0/25, SamplesPerSec=6.302019280317165
```

**Review by jeffra — APPROVED** [review]

**Comment by tjruwase** [comment]
> after your last commit other debug prints replaced the old ones, now I get these for each step:
> 
> ```
> [2021-03-10 18:22:31,608] [INFO] [logging.py:60:log_dist] [Rank 0] step=25, skipped=5, lr=[1.446140557591026e-05], mom=[[0.8, 0.999]]
> [2021-03-10 18:22:31,608] [INFO] [timer.py:154:stop] 0/25, SamplesPerSec=6.302019280317165
> ```
> 
> It looks like those were added when you re-based this PR branch

What is your steps_per_print, is it 25?

**Comment by stas00** [comment]
You're correct, I had `steps_per_print` set to 1 in the config - my bad. I retested and all is perfect then!

Thank you!

**Pull request merged**
