### PR TITLE
Add Ascend NPU accelerator support

### PR DESCRIPTION
**Pull request by CurryRice233**
Add Ascend NPU accelerator support

### CODE REVIEW

**Comment by CurryRice233** [comment]
@microsoft-github-policy-service agree

**Comment by tjruwase** [comment]
@CurryRice233, thanks for this PR. It looks very exciting. Do you mind sharing any background or docs about the Ascend NPU?

**Comment by CurryRice233** [comment]
> @CurryRice233, thanks for this PR. It looks very exciting. Do you mind sharing any background or docs about the Ascend NPU?

thanks for your reply. Ascend NPU is a AI processor that support AI frameworks like PyTorch, TensorFlow, etc. So, i think its possible run Deepspeed on NPU to train foundation model. Their website: https://www.hiascend.com/en/

**Review by tjruwase — APPROVED** [review]

**Comment by CurryRice233** [comment]
@tjruwase @jeffra @xiaoxiawu-microsoft Sorry for annoying, can you guys merge this PR ?

**Comment by tjruwase** [comment]
@CurryRice233, apologies for the delay in merging this. I have setup for auto-merge but now it seems formatting is broken.

**Comment by CurryRice233** [comment]
> @CurryRice233, apologies for the delay in merging this. I have setup for auto-merge but now it seems formatting is broken.

no problem, it will be fixed with new commit.

**Pull request merged**
