### PR TITLE
tl.dot updated  https://github.com/openai/triton/issues/1098  

### PR DESCRIPTION
**Pull request by bmedishe**
I got this error when trying to run stable_diffusion inference with deepspeed 
TypeError: dot() got an unexpected keyword argument 'trans_b'

Issue found on triton with the same error : [TypeError: dot() got an unexpected keyword argument 'trans_b'](https://github.com/openai/triton/issues/1098#top)
solution suggested was to use `qk += tl.dot(q, tl.trans(k))` , inplace of  `qk += tl.dot(q, k, trans_b=True)`

### CODE REVIEW

**Comment by mrwyattii** [comment]
@bmedishe have you tested this with a stable diffusion model? It causes DeepSpeed to hang for me.

**Comment by bmedishe** [comment]
> @bmedishe have you tested this with a stable diffusion model? It causes DeepSpeed to hang for me.
@mrwyattii  Hi , I see a hang on AMD GPU too, what version of triton should I be using to have working 
`qk += tl.dot(q, k, trans_b=True)`
After this PR  [Merge triton-mlir branch - Complete rewrite of the backend from scratch](https://github.com/openai/triton/pull/1004 ) `qk += tl.dot(q, k, trans_b=True)` throws TypeError

**Comment by abhijitpal1247** [comment]
I am facing the same issue, any updates?

**Comment by DEQDON** [comment]
Same here. This fix hangs on Nvidia RTX 3090.

**Comment by mrwyattii** [comment]
> @mrwyattii Hi , I see a hang on AMD GPU too, what version of triton should I be using to have working `qk += tl.dot(q, k, trans_b=True)`

https://github.com/microsoft/DeepSpeed/blob/d92539509b1e9a6178cfdb921d5080e76f690bce/requirements/requirements-sd.txt#L2

**Pull request closed without merging**
