### PR TITLE
Universal checkpoint for zero stage 1

### PR DESCRIPTION
**Pull request by tjruwase**
Enable universal checkpoint for zero stages 1
Support fp16 training
Fix TP dimension expansion bug
Replace BLOOM-specific hardcoding to enable generalization
@stas00, FYI

### CODE REVIEW

**Comment by stas00** [comment]
Awesome work, @tjruwase!

At one point it'd be great to have an instructional document of how a user can go from one ZeRO topology to another using the existing checkpoint. Thank you!

**Comment by tjruwase** [comment]
> At one point it'd be great to have an instructional document of how a user can go from one ZeRO topology to another using the existing checkpoint. Thank you!

**Review by mrwyattii — APPROVED** [review]
LGTM, but I would like to get #2216 merged prior to merging this, so we can verify all unit tests are passing (especially the elastic checkpoint tests).

**Comment by mayank31398** [comment]
https://github.com/microsoft/DeepSpeed/issues/2382 is related to this

**Pull request merged**
