### PR TITLE
[NPU] Add HcclBackend for 1-bit adam, 1-bit lamb, 0/1 adam

### PR DESCRIPTION
**Pull request by RUAN-ZX**
To support NPU devices fulfilling feature requirements like 1-bit Adam, 1-bit Lamb, 0/1 Adam, I add HcclBackend and its corresponding import logics.
See what we have already done in #4567 .

### CODE REVIEW

**Comment by RUAN-ZX** [comment]
@conglongli @awan-10 Would you please take a look? Thank you :)

**Comment by RUAN-ZX** [comment]
@conglongli @awan-10 @tjruwase Could you please review this PR, cause we have some following PRs based on it. If you have any question, please tell me, I will be happy to solve it. Thank you :)

**Comment by CurryRice233** [comment]
> @RUAN-ZX Since we don't have the hardware, we will only review/approve based on whether your PR pass all our unit tests (it already failed the formatting test). And we would have to redirect all related future bug reports to you.

Of course, we'll fix all the bugs with NPU. On the other hand, is it possible to add NPU unit tests to the workflow if we provide an NPU CI server?

**Comment by conglongli** [comment]
> > @RUAN-ZX Since we don't have the hardware, we will only review/approve based on whether your PR pass all our unit tests (it already failed the formatting test). And we would have to redirect all related future bug reports to you.
> 
> Of course, we'll fix all the bugs with NPU. On the other hand, is it possible to add NPU unit tests to the workflow if we provide an NPU CI server?

@CurryRice233 please contact @tjruwase for this kind of requests.

**Review by conglongli — APPROVED** [review]

**Comment by RUAN-ZX** [comment]
@conglongli, could you review and merge [a latest commit](https://github.com/microsoft/DeepSpeed/pull/4733/commits/d0cb8e60f7d6214e31f81305e76ade809bc997ad)? Sorry for this inconvenience and thank you :)

**Comment by conglongli** [comment]
> @conglongli, could you review and merge [a latest commit](https://github.com/microsoft/DeepSpeed/pull/4733/commits/d0cb8e60f7d6214e31f81305e76ade809bc997ad)? Sorry for this inconvenience and thank you :)

@RyanInnerpeace In the future please avoid adding last minute commit which will break our auto-merge mechanism and keep delaying the PR merge.

**Pull request merged**
