### PR TITLE
Add the policy to run llama model from the official repo

### PR DESCRIPTION
**Pull request by RezaYazdaniAminabadi**
This PR adds the support for Llama2 using the official implementation of llama using [llama repo](https://www.bing.com/ck/a?!&&p=830be5722d076bf0JmltdHM9MTY5NDQ3NjgwMCZpZ3VpZD0wNjNlMWQ1Ni0yMGEzLTZkMWUtMzVmMy0xMjA4MjE3NDZjNTUmaW5zaWQ9NTIwOA&ptn=3&hsh=3&fclid=063e1d56-20a3-6d1e-35f3-120821746c55&psq=repo%3afacebookresearch%2fllama&u=a1aHR0cHM6Ly9naXRodWIuY29tL2ZhY2Vib29rcmVzZWFyY2gvbGxhbWE&ntb=1)

This is now working for all the llama variant except the ones that require kv-sharing. 
Next will add the support for the KV-shared architecture.

### CODE REVIEW

**Comment by mpjlu** [comment]
This PR is for the official llama repo, but named llama2. User will be confusing for the file and class names.
Since the 7B and 13B model arch of  llama and llama2 is the same, now DS can run llama 2 7B and 13B HF model, just need to support 70B llama 2 model.
It is better to enable 70B llama2 model on the current llama code.

**Comment by RezaYazdaniAminabadi** [comment]
> This PR is for the official llama repo, but named llama2. User will be confusing for the file and class names. Since the 7B and 13B model arch of llama and llama2 is the same, now DS can run llama 2 7B and 13B HF model, just need to support 70B llama 2 model. It is better to enable 70B llama2 model on the current llama code.

Hi @mpjlu,

Thanks for the comment.
Agreed on this, and this policy is just a secondary one for me to try with the official repo, as getting access to the llama models on HF takes a long processing time. I will name them better!
Also, I am working on adding the 70B support.
Best,
Reza

**Comment by RezaYazdaniAminabadi** [comment]
I added some test for checking the performance and accuracy of this PR using [a fork](https://github.com/RezaYazdaniAminabadi/llama/tree/add-ds-inference) of the llama code-base.
There are some script that you can use to run different model configuration, [here](https://github.com/RezaYazdaniAminabadi/llama/blob/add-ds-inference/run_text_generation.sh).
I am seeing about 2.8x performance speedup when using ds-inference for the Llama-70B model using same example used in the repo (will add more test to check the performance more extensively):
```
[2023-09-13 13:23:09,286] [INFO] [logging.py:96:log_dist] [Rank 0] DeepSpeed-Inference config: {'layer_id': 0, 'hidden_size': 8192, 'intermediate_size': 28672, 'heads': 64, 'num_hidden_layers': -1, 'dtype': torch.float16, 'pre_layer_norm': True, 'norm_type': <NormType.RMSNorm: 3>, 'local_rank': -1, 'stochastic_mode': False, 'epsilon': 1e-05, 'mp_size': 8, 'scale_attention': True, 'triangular_masking': True, 'local_attention': False, 'window_size': 1, 'rotary_dim': 128, 'rotate_half': False, 'rotate_every_two': True, 'return_tuple': False, 'mlp_after_attn': True, 'mlp_act_func_type': <ActivationFuncType.GATED_SILU: 4>, 'specialized_mode': False, 'training_mp_size': 1, 'bigscience_bloom': False, 'max_out_tokens': 1024, 'min_out_tokens': 1, 'scale_attn_by_inverse_layer_idx': False, 'enable_qkv_quantization': False, 'use_mup': False, 'return_single_tuple': False, 'set_empty_params': False, 'transposed_mode': False, 'use_triton': False, 'triton_autotune': False, 'num_kv': 8}
Loading extension module transformer_inference...
------------------------------------------------------
Free memory : 35.154175 (GigaBytes)  
Total memory: 79.169678 (GigaBytes)  
Requested memory: 3.875000 (GigaBytes) 
Setting maximum total tokens (input + output) to 1024 
WorkSpace: 0x7f9798000000 
------------------------------------------------------
baseline: generation time 10.940 sec for generating x tokens.
ds-inference: generation time 3.938 sec for generating x tokens.
speeup: 2.778x
```

**Comment by mpjlu** [comment]
> I added some test for checking the performance and accuracy of this PR using [a fork](https://github.com/RezaYazdaniAminabadi/llama/tree/add-ds-inference) of the llama code-base. There are some script that you can use to run different model configuration, [here](https://github.com/RezaYazdaniAminabadi/llama/blob/add-ds-inference/run_text_generation.sh). I am seeing about 2.8x performance speedup (using 8 A100 GPUs) when using ds-inference for the Llama-70B model using same example used in the repo (will add more test to check the performance more extensively):
> 
> ```
> [2023-09-13 13:23:09,286] [INFO] [logging.py:96:log_dist] [Rank 0] DeepSpeed-Inference config: {'layer_id': 0, 'hidden_size': 8192, 'intermediate_size': 28672, 'heads': 64, 'num_hidden_layers': -1, 'dtype': torch.float16, 'pre_layer_norm': True, 'norm_type': <NormType.RMSNorm: 3>, 'local_rank': -1, 'stochastic_mode': False, 'epsilon': 1e-05, 'mp_size': 8, 'scale_attention': True, 'triangular_masking': True, 'local_attention': False, 'window_size': 1, 'rotary_dim': 128, 'rotate_half': False, 'rotate_every_two': True, 'return_tuple': False, 'mlp_after_attn': True, 'mlp_act_func_type': <ActivationFuncType.GATED_SILU: 4>, 'specialized_mode': False, 'training_mp_size': 1, 'bigscience_bloom': False, 'max_out_tokens': 1024, 'min_out_tokens': 1, 'scale_attn_by_inverse_layer_idx': False, 'enable_qkv_quantization': False, 'use_mup': False, 'return_single_tuple': False, 'set_empty_params': False, 'transposed_mode': False, 'use_triton': False, 'triton_autotune': False, 'num_kv': 8}
> Loading extension module transformer_inference...
> ------------------------------------------------------
> Free memory : 35.154175 (GigaBytes)  
> Total memory: 79.169678 (GigaBytes)  
> Requested memory: 3.875000 (GigaBytes) 
> Setting maximum total tokens (input + output) to 1024 
> WorkSpace: 0x7f9798000000 
> ------------------------------------------------------
> baseline: generation time 10.940 sec for generating x tokens.
> ds-inference: generation time 3.938 sec for generating x tokens.
> speeup: 2.778x
> ```

Does this PR support llama-2-70B model?  "Llama-70B model" is llama 1 or llama 2?

**Comment by RezaYazdaniAminabadi** [comment]
> > I added some test for checking the performance and accuracy of this PR using [a fork](https://github.com/RezaYazdaniAminabadi/llama/tree/add-ds-inference) of the llama code-base. There are some script that you can use to run different model configuration, [here](https://github.com/RezaYazdaniAminabadi/llama/blob/add-ds-inference/run_text_generation.sh). I am seeing about 2.8x performance speedup (using 8 A100 GPUs) when using ds-inference for the Llama-70B model using same example used in the repo (will add more test to check the performance more extensively):
> > ```
> > [2023-09-13 13:23:09,286] [INFO] [logging.py:96:log_dist] [Rank 0] DeepSpeed-Inference config: {'layer_id': 0, 'hidden_size': 8192, 'intermediate_size': 28672, 'heads': 64, 'num_hidden_layers': -1, 'dtype': torch.float16, 'pre_layer_norm': True, 'norm_type': <NormType.RMSNorm: 3>, 'local_rank': -1, 'stochastic_mode': False, 'epsilon': 1e-05, 'mp_size': 8, 'scale_attention': True, 'triangular_masking': True, 'local_attention': False, 'window_size': 1, 'rotary_dim': 128, 'rotate_half': False, 'rotate_every_two': True, 'return_tuple': False, 'mlp_after_attn': True, 'mlp_act_func_type': <ActivationFuncType.GATED_SILU: 4>, 'specialized_mode': False, 'training_mp_size': 1, 'bigscience_bloom': False, 'max_out_tokens': 1024, 'min_out_tokens': 1, 'scale_attn_by_inverse_layer_idx': False, 'enable_qkv_quantization': False, 'use_mup': False, 'return_single_tuple': False, 'set_empty_params': False, 'transposed_mode': False, 'use_triton': False, 'triton_autotune': False, 'num_kv': 8}
> > Loading extension module transformer_inference...
> > ------------------------------------------------------
> > Free memory : 35.154175 (GigaBytes)  
> > Total memory: 79.169678 (GigaBytes)  
> > Requested memory: 3.875000 (GigaBytes) 
> > Setting maximum total tokens (input + output) to 1024 
> > WorkSpace: 0x7f9798000000 
> > ------------------------------------------------------
> > baseline: generation time 10.940 sec for generating x tokens.
> > ds-inference: generation time 3.938 sec for generating x tokens.
> > speeup: 2.778x
> > ```
> 
> Does this PR support llama-2-70B model? "Llama-70B model" is llama 1 or llama 2?

It supports Llama-2-70B. Of course, it is a llama-2 model

**Comment by mpjlu** [comment]
> > > I added some test for checking the performance and accuracy of this PR using [a fork](https://github.com/RezaYazdaniAminabadi/llama/tree/add-ds-inference) of the llama code-base. There are some script that you can use to run different model configuration, [here](https://github.com/RezaYazdaniAminabadi/llama/blob/add-ds-inference/run_text_generation.sh). I am seeing about 2.8x performance speedup (using 8 A100 GPUs) when using ds-inference for the Llama-70B model using same example used in the repo (will add more test to check the performance more extensively):
> > > ```
> > > [2023-09-13 13:23:09,286] [INFO] [logging.py:96:log_dist] [Rank 0] DeepSpeed-Inference config: {'layer_id': 0, 'hidden_size': 8192, 'intermediate_size': 28672, 'heads': 64, 'num_hidden_layers': -1, 'dtype': torch.float16, 'pre_layer_norm': True, 'norm_type': <NormType.RMSNorm: 3>, 'local_rank': -1, 'stochastic_mode': False, 'epsilon': 1e-05, 'mp_size': 8, 'scale_attention': True, 'triangular_masking': True, 'local_attention': False, 'window_size': 1, 'rotary_dim': 128, 'rotate_half': False, 'rotate_every_two': True, 'return_tuple': False, 'mlp_after_attn': True, 'mlp_act_func_type': <ActivationFuncType.GATED_SILU: 4>, 'specialized_mode': False, 'training_mp_size': 1, 'bigscience_bloom': False, 'max_out_tokens': 1024, 'min_out_tokens': 1, 'scale_attn_by_inverse_layer_idx': False, 'enable_qkv_quantization': False, 'use_mup': False, 'return_single_tuple': False, 'set_empty_params': False, 'transposed_mode': False, 'use_triton': False, 'triton_autotune': False, 'num_kv': 8}
> > > Loading extension module transformer_inference...
> > > ------------------------------------------------------
> > > Free memory : 35.154175 (GigaBytes)  
> > > Total memory: 79.169678 (GigaBytes)  
> > > Requested memory: 3.875000 (GigaBytes) 
> > > Setting maximum total tokens (input + output) to 1024 
> > > WorkSpace: 0x7f9798000000 
> > > ------------------------------------------------------
> > > baseline: generation time 10.940 sec for generating x tokens.
> > > ds-inference: generation time 3.938 sec for generating x tokens.
> > > speeup: 2.778x
> > > ```
> > 
> > 
> > Does this PR support llama-2-70B model? "Llama-70B model" is llama 1 or llama 2?
> 
> It supports Llama-2-70B. Of course, it is a llama-2 model

llama-2-70b is KV-shared architecture, so this PR support KV-shared architecture, right?

**Comment by RezaYazdaniAminabadi** [comment]
> > > > I added some test for checking the performance and accuracy of this PR using [a fork](https://github.com/RezaYazdaniAminabadi/llama/tree/add-ds-inference) of the llama code-base. There are some script that you can use to run different model configuration, [here](https://github.com/RezaYazdaniAminabadi/llama/blob/add-ds-inference/run_text_generation.sh). I am seeing about 2.8x performance speedup (using 8 A100 GPUs) when using ds-inference for the Llama-70B model using same example used in the repo (will add more test to check the performance more extensively):
> > > > ```
> > > > [2023-09-13 13:23:09,286] [INFO] [logging.py:96:log_dist] [Rank 0] DeepSpeed-Inference config: {'layer_id': 0, 'hidden_size': 8192, 'intermediate_size': 28672, 'heads': 64, 'num_hidden_layers': -1, 'dtype': torch.float16, 'pre_layer_norm': True, 'norm_type': <NormType.RMSNorm: 3>, 'local_rank': -1, 'stochastic_mode': False, 'epsilon': 1e-05, 'mp_size': 8, 'scale_attention': True, 'triangular_masking': True, 'local_attention': False, 'window_size': 1, 'rotary_dim': 128, 'rotate_half': False, 'rotate_every_two': True, 'return_tuple': False, 'mlp_after_attn': True, 'mlp_act_func_type': <ActivationFuncType.GATED_SILU: 4>, 'specialized_mode': False, 'training_mp_size': 1, 'bigscience_bloom': False, 'max_out_tokens': 1024, 'min_out_tokens': 1, 'scale_attn_by_inverse_layer_idx': False, 'enable_qkv_quantization': False, 'use_mup': False, 'return_single_tuple': False, 'set_empty_params': False, 'transposed_mode': False, 'use_triton': False, 'triton_autotune': False, 'num_kv': 8}
> > > > Loading extension module transformer_inference...
> > > > ------------------------------------------------------
> > > > Free memory : 35.154175 (GigaBytes)  
> > > > Total memory: 79.169678 (GigaBytes)  
> > > > Requested memory: 3.875000 (GigaBytes) 
> > > > Setting maximum total tokens (input + output) to 1024 
> > > > WorkSpace: 0x7f9798000000 
> > > > ------------------------------------------------------
> > > > baseline: generation time 10.940 sec for generating x tokens.
> > > > ds-inference: generation time 3.938 sec for generating x tokens.
> > > > speeup: 2.778x
> > > > ```
> > > 
> > > 
> > > Does this PR support llama-2-70B model? "Llama-70B model" is llama 1 or llama 2?
> > 
> > 
> > It supports Llama-2-70B. Of course, it is a llama-2 model
> 
> the attention of llama-2-70b is GQA(KV-shared arch) , this PR support llama2 in a not KV-shared method, so the KV-cache memory is the same as MHA, right?

right, that will be added next

**Review by awan-10 — APPROVED** [review]

**Review by mrwyattii — APPROVED** [review]

**Review by lekurile — APPROVED** [review]

**Comment by jsheng-jian** [comment]
@RezaYazdaniAminabadi How is the progress of adding GQA to support the LLaMA2-70B model? We would like to see if any help is needed to expedite it.

**Pull request merged**
