### PR TITLE
fix: fix BF16_Optimizer compatibility issue

### PR DESCRIPTION
**Pull request by shjwudp**
Fix BF16_Optimizer compatibility issue with optimizer state 0-dim tensor, `tensor.narrow` does not support 0-dim tensor.

### CODE REVIEW

**Comment by tjruwase** [comment]
@shjwudp, thanks for this PR. Can you share a bit more context on when this fails?

**Comment by shjwudp** [comment]
> @shjwudp, thanks for this PR. Can you share a bit more context on when this fails?

OK, this is really an edge case, in fairseq's Adafactor implementation, the RMS is calculated by the formula `tensor.norm(2) / (tensor.numel() ** 0.5) `, which is a 0-dim tensor.
https://github.com/facebookresearch/fairseq/blob/main/fairseq/optim/adafactor.py#L223

**Review by tjruwase — APPROVED** [review]

**Comment by tjruwase** [comment]
Interesting, thanks for sharing. So, to clarify, are you applying bf16_optimizer to adafactor for large model training? If so, we would be very interested in your experience. I suspect there might be issues with checkpoint load/stores, perhaps :).

**Comment by toriving** [comment]
@shjwudp 
hello.
I am using bf16 adafactor same as you.
In my case, I use the Huggingface's adafactor, and when I use it with deepspeed, the loss does not drop and it is not learning.
Have you ever experienced any of these problems?
Or, what happens if you learn without modifying this?

**Pull request merged**
