### PR TITLE
Improve overflow handling

### LINKED ISSUE #2911: [BUG] overflow warning needs to be different for fp16 and non-fp16
**Describe the bug**

This code has an issue when it is run under non-fp16 regime.

https://github.com/microsoft/DeepSpeed/blob/da84e60d98d2e90f6f2094a219c98c8b41582eb9/deepspeed/runtime/zero/stage3.py#L1837-L1842

There are no scalers under bf16/fp32. So this warning is alarming to see - we rushed to see if somehow the config was broken, but it wasn't.

It should only say the `Attempted loss scale:...` part under fp16.

Most likely the same applies to its counterpart in stage 1/2.

Also do you think it'd be helpful to tell the user specifically if it's Inf vs. NaN? Since NaN isn't really an overflow or does it? Perhaps one of you with a more rigorous math background knows better. I think overflow is one of many types of NaN, thus NaN isn't always on Overflow. Please correct me if I'm wrong. 

The reason I'm asking this question is to help the user to know what to look for, NaNs, Infinity, else.

@tjruwase

### PR DESCRIPTION
**Pull request by tjruwase**
Fix #2911 

1. Refactors loss scaling code
2. Separates the overflow warning into 2 parts, only the 2nd part gets emitted when fp16 is used

### CODE REVIEW

**Comment by tjruwase** [comment]
@stas00, FYI

**Comment by stas00** [comment]
So just to verify this PR:
1. refactors some code
2. separates the warning into 2 parts, only the 2nd part relevant to fp16
correct?

That looks great to me - thank you for improving it, Tunji!

**Comment by tjruwase** [comment]
Yes, and I have copied your apt description. 

What remains are improvements to the error message:
1. Distinguishing the type of overflow: nans and/or infs
2.

**Comment by stas00** [comment]
on transformers CI tests you're running into disc space issues:

```
Traceback (most recent call last):
  File "/tmp/actions-runner/_work/DeepSpeed/DeepSpeed/transformers/examples/pytorch/language-modeling/run_clm.py", line 625, in <module>
    main()
  File "/tmp/actions-runner/_work/DeepSpeed/DeepSpeed/transformers/examples/pytorch/language-modeling/run_clm.py", line 329, in main
    raw_datasets = load_dataset(
  File "/tmp/actions-runner/_work/DeepSpeed/DeepSpeed/unit-test-venv/lib/python3.8/site-packages/datasets/load.py", line 1731, in load_dataset
    builder_instance.download_and_prepare(
  File "/tmp/actions-runner/_work/DeepSpeed/DeepSpeed/unit-test-venv/lib/python3.8/site-packages/datasets/builder.py", line 586, in download_and_prepare
    raise OSError(
OSError: Not enough disk space. Needed: Unknown size (download: Unknown size, generated: Unknown size, post-processed: Unknown size)
```

**Review by jeffra — APPROVED** [review]

**Pull request merged**
