### PR TITLE
Fix type checking of offload optimizer before checked class was imported

### PR DESCRIPTION
**Pull request by ollmer**
This bug prevents to run Megatron-LM 10B offload training example

### CODE REVIEW

**Comment by tjruwase** [comment]
@ollmer Thanks for creating this PR. Can you please share a log of the error that this fixes?

**Comment by rocm-mici** [comment]
Can one of the admins verify this patch?

**Comment by tjruwase** [comment]
@ollmer, is this needed?

**Comment by awan-10** [comment]
Closing this very old PR as it is no longer relevant (Megatron-LM has been deprecated and Megatron-DeepSpeed has a different codebase altogether). Please reopen if needed.

**Pull request closed without merging**
