### PR TITLE
Modify deepspeed_lr_schedules

### PR DESCRIPTION
**Pull request by chunyang-wen**
+ Add `args` module to store all parser needed by deepspeed
  + Still exists other work to achieve this target: arguments in deepspeed_run/deepspeed_launch
+ move constants to constants module
  + Move constants to a central place for easy reference and management
+ clean up duplicate code

### CODE REVIEW

**Comment by tjruwase** [comment]
@chunyang-wen Thanks for your contribution.

**Comment by chunyang-wen** [comment]
@ShadenSmith @jeffra Please double check the code in order not to break things that I do not know.

**Comment by chunyang-wen** [comment]
ping @jeffra @ShadenSmith

**Comment by ShadenSmith** [comment]
Hi @chunyang-wen , sorry for the delay. The PR looks great and we're just discussing internally the best route to add some test coverage to this part of DeepSpeed. It's not currently covered well (from before, not a criticism of this PR).

**Pull request closed without merging**
