### PR TITLE
feat: add Lion

### PR DESCRIPTION
**Pull request by enneamer**
Implement Lion optimizer as specified by [Chen, et al][1]. The optimizer seems welcomed by some diffusion model developers.

[1]: https://arxiv.org/abs/2302.06675

### CODE REVIEW

**Comment by enneamer** [comment]
@microsoft-github-policy-service agree

**Comment by enneamer** [comment]
@mrwyattii, I have added similar unit tests. I also added code to allow creating optimizer through JSON configuration. I know that there is a separate list for DeepSpeed ZeRO-supported optimizers. Should I add it there as well?

**Comment by mrwyattii** [comment]
@enneamer yes, please add to the list here:
https://github.com/microsoft/DeepSpeed/blob/c58146471e7ba7df9791f27bdb6c3f2afa0bd3e5/deepspeed/runtime/zero/utils.py#L39

Also take a look at the failing unit tests! thank you

**Comment by enneamer** [comment]
@mrwyattii , I have added both optimizers to the supported optimizer list.

I have added some fixes and ran the newly added unit tests locally. It seems fine. However, my test machine is an ARM64 CUDA server, so the results of CPU/CUDA comparison test might differ from those of the CI check here. Let's see.

**Comment by enneamer** [comment]
@mrwyattii , I just rebased the branch and noticed CI needs your approval again. Thank you for your help.

**Comment by mrwyattii** [comment]
> @mrwyattii , I just rebased the branch and noticed CI needs your approval again. Thank you for your help.

Just approved. Sorry for the delay, I was on vacation last week. I will get this merged this week. Thank you again for the contribution!

**Comment by enneamer** [comment]
@mrwyattii , no problem at all. I wish you had a wonderful break.

It seems that the optimizers are fine. The failed tests seem to be related to ongoing development in DeepSpeed inference.

**Review by tjruwase — APPROVED** [review]

**Comment by tjruwase** [comment]
@enneamer, thanks for this incredible contribution. LGTM.

**Review by mrwyattii — APPROVED** [review]

**Pull request merged**
