### PR TITLE
Fix transformers/torch errors on nn.RMSNorm by pinning transformers.

### PR DESCRIPTION
**Pull request by loadams**
HPU pipeline was failing due to updated transformers package that seems to have a dependency on torch 2.4: https://github.com/microsoft/DeepSpeed/actions/runs/10586654075/job/29335873815

Opened an issue with transformers to investigate: https://github.com/huggingface/transformers/issues/33176

CC: @nelyahu - we can also fix this when/if there is a package with torch 2.4

### CODE REVIEW

**Comment by loadams** [comment]
Should be fixed in latest PR to HF Transformers - won't need to complete this PR but leaving until transformers PR is merged.

**Comment by nelyahu** [comment]
@loadams on 1.18.0 we will upgrade to pt2.4.0.
CC: @vshekhawat-hlab

**Comment by loadams** [comment]
> @loadams on 1.18.0 we will upgrade to pt2.4.0. CC: @vshekhawat-hlab

Thanks @nelyahu - turns out this is a bug in transformers and we will need that fixed regardless, but good to know, thanks!

**Comment by loadams** [comment]
PR in transformers is here: https://github.com/huggingface/transformers/pull/33177

**Comment by nelyahu** [comment]
@loadams it seems that the Gaudi2 pipeline is still broken.
Are you planning to wait till PR for transformers will be merged and included in a version? 
i think it might take a while. no?

**Comment by loadams** [comment]
The PR has merged into transformers (took longer than anticipated) but it looks to be running again, so no need to pin anything.

**Pull request closed without merging**
