### PR TITLE
Launcher mode with SSH bypass

### PR DESCRIPTION
**Pull request by dogacancolak-kensho**
https://github.com/microsoft/DeepSpeed/issues/5510

### CODE REVIEW

**Comment by adk9** [comment]
LGTM. @dogacancolak-kensho can you please sign the CLA?

**Review by adk9 — APPROVED** [review]

**Review by tjruwase — APPROVED** [review]

**Comment by dogacancolak-kensho** [comment]
@microsoft-github-policy-service agree company="Kensho Technologies, LLC"

**Comment by dogacancolak-kensho** [comment]
Seems like some checks can't find a runner to pick up the job, and one test failed due to seemingly transient errors. Does it require some intervention by maintainers @adk9 @tjruwase @loadams?

**Comment by loadams** [comment]
> Seems like some checks can't find a runner to pick up the job, and one test failed due to seemingly transient errors. Does it require some intervention by maintainers @adk9 @tjruwase @loadams?

@dogacancolak-kensho - we are aware of this and are working to fix this.  We will re-queue the builds when things are resolved.

**Pull request merged**
