### PR TITLE
fix uneven issue & add balance autotp

### PR DESCRIPTION
**Pull request by Yejing-Lai**
This PR aims to balance the shard size of each worker as even as possible.
1. We refactor the tp_shard logic that can make AutoTP work when split_shape % num_kv_heads != 0.
2. When num_kv_heads is defined, the attention module relies on it to sharding, but the mlp and lm_head modules can use near even division to get more balance shard. It will get better performance.

### CODE REVIEW

**Comment by Yejing-Lai** [comment]
Hi @RezaYazdaniAminabadi @delock. Could you please help review this PR? Thanks~

**Comment by delock** [comment]
Hi @Yejing-Lai  can you give some explain on the need to have grainularity of 64 elements?
https://github.com/microsoft/DeepSpeed/pull/4697/files#diff-214e32993d5440123080193836e988f024771aa4f6931c614ef9ad42a493f398R31

**Comment by Yejing-Lai** [comment]
> Hi @Yejing-Lai can you give some explaination on the need to have grainularity of 64 elements? https://github.com/microsoft/DeepSpeed/pull/4697/files#diff-214e32993d5440123080193836e988f024771aa4f6931c614ef9ad42a493f398R31

DNN library favors tensor size in granularity of power of 2, we pick 64 as a common granularity size.

**Comment by delock** [comment]
Hi @RezaYazdaniAminabadi , can this PR be reviewed?  This PR improves AutoTP sharding when number of heads cannot be divided by number of ranks.  MLP layers will have better load balance when running AutoTP on 3 devices or 3 CPU sub-NUMA clusters.

**Comment by tjruwase** [comment]
@Yejing-Lai, please help resolve conflict.

**Comment by Yejing-Lai** [comment]
> @Yejing-Lai, please help resolve conflict.

Hi @tjruwase. I resolved the conflict. Can you approve the workflows? Thanks~

**Comment by Yejing-Lai** [comment]
Hi @tjruwase. The conflict had been resolved. Could you please help review this PR? Thanks~

**Comment by delock** [comment]
Hi @tjruwase is this PR under review state or merge state?  We are working on Intel Extension for PyTorch release and want to know whether this PR will be included in DeepSpeed next release.  Thanks!

**Comment by tjruwase** [comment]
> Hi @tjruwase is this PR under review state or merge state? We are working on Intel Extension for PyTorch release and want to know whether this PR will be included in DeepSpeed next release. Thanks!

@delock, sorry for the delay. This should be reviewed soon and will be included in next release.

**Review by lekurile — APPROVED** [review]

**Review by awan-10 — APPROVED** [review]

**Pull request merged**
