### PR TITLE
Modify inference engine

### PR DESCRIPTION
**Pull request by chunyang-wen**
It seems that `engine` module under inference package is not well developed. This PR tries to 
+ Replace `assert` with `raise` and additional information. Actually `assert` can be turned off sometimes.
+ Remove useless import
+ Fix a bug about return_tuple
+ modify the function name of `_check_quantize_setting` to `_init_quantization_setting`

More documentation about this module is needed.

### CODE REVIEW

**Comment by chunyang-wen** [comment]
ping @RezaYazdaniAminabadi

**Comment by RezaYazdaniAminabadi** [comment]
Hi @chunyang-wen 

Thanks for going through the inference engine-API and make these nice modifications. I will put more information on the parameters description. 
Thanks,
Reza

**Comment by chunyang-wen** [comment]
So should we merge this PR first and then you add further improvement or I just close it?

**Comment by RezaYazdaniAminabadi** [comment]
> So should we merge this PR first and then you add further improvement or I just close it?

No, let me please add them and we can merge it soon. Thanks

**Comment by chunyang-wen** [comment]
> > So should we merge this PR first and then you add further improvement or I just close it?
> 
> No, let me please add them and we can merge it soon. Thanks

Sure, thanks.

**Review by RezaYazdaniAminabadi — APPROVED** [review]

**Comment by chunyang-wen** [comment]
Have no idea why the check fails.

**Comment by chunyang-wen** [comment]
@jeffra please merge or open auto merge. Thanks.

**Comment by jeffra** [comment]
We had a CI runner failure earlier due to some new runners being misconfigured. Should be fixed now.

**Pull request merged**
