### PR TITLE
Fixed the Windows build.

### PR DESCRIPTION
**Pull request by costin-eseanu**
Fixed the Windows build.

Fixes applied:
- Remove some more ops that don't build on Windows.
- Remove the use of symlinks that didn't work correctly and replace with `shutil.copytree()`.
- Small fixes to make the C++ code compile.

Tested with Python 3.9 and CUDA 12.1.

### CODE REVIEW

**Comment by tjruwase** [comment]
@costin-eseanu, see below to resolve formatting
https://github.com/microsoft/DeepSpeed/blob/master/CONTRIBUTING.md

**Review by loadams — APPROVED** [review]

**Comment by ChangxingJiang** [comment]
this commit may cause a build error. There use the wrong path and `shutil.copytree` cannot cover the exists file.

```python
if sys.platform == "win32":
    shutil.copytree('.\\csrc', '.\\deepspeed\\ops')
    shutil.copytree('.\\op_builder', '.\\deepspeed\\ops')
    shutil.copytree('.\\accelerator', '.\\deepspeed\\accelerator')
    egg_info.manifest_maker.template = 'MANIFEST_win.in'
```

**Comment by loadams** [comment]
Hi @ChangxingJiang - this should be fixed in #5609, can you confirm there?

**Comment by ChangxingJiang** [comment]
> Hi @ChangxingJiang - this should be fixed in #5609, can you confirm there?

Yes, is useful.

**Pull request merged**
