### PR TITLE
Fix exception handling in get_all_ranks_from_group() function

### PR DESCRIPTION
**Pull request by HeyangQin**
In the latest Pytorch nightly, the exception thrown from `torch.distributed.distributed_c10d.get_global_rank()` is changed from `RuntimeError` to `ValueError` so we need to update our try-catch in `deepspeed.comm`

Tested with torch version 2.3.0.dev20231221+cu121

Fixes: https://github.com/microsoft/DeepSpeed/issues/4853

### CODE REVIEW

**Comment by HeyangQin** [comment]
This PR is to address issue https://github.com/microsoft/DeepSpeed/issues/4853

**Comment by stas00** [comment]
I confirm that it solves https://github.com/microsoft/DeepSpeed/issues/4853 - thank you, @HeyangQin!

**Comment by stas00** [comment]
BTW, you can add to OP:
```
Fixes: https://github.com/microsoft/DeepSpeed/issues/4853
```
and it'll automatically close the Issue when this gets merged.

**Review by awan-10 — APPROVED** [review]

**Comment by apoorvkh** [comment]
Hey, is it possible to include this change in a patch release? Thanks!

**Comment by tjruwase** [comment]
@apoorvkh, a release should drop in the next few days.

**Pull request merged**
