### PR TITLE
add bf16 cuda kernel support

### PR DESCRIPTION
**Pull request by dc3671**
- This PR will add bf16 support for part of cuda kernels used by BLOOM with simple C++ template implementation. 

- It's related to https://github.com/microsoft/DeepSpeed/pull/3041, and will benefit comparison between cuda and cpu.

- Also, some existed fp16 implementation is combined with fp32 version if possible.

Please help review @tjruwase @jeffra  thanks~

cc @delock @rogerxfeng8

### CODE REVIEW

**Comment by dc3671** [comment]
@microsoft-github-policy-service agree company="intel"

**Comment by dc3671** [comment]
@jeffra Could you plz help enabling CI workflow? I added some fixes to bypass bf16 if cuda arch does not support it.

**Comment by dc3671** [comment]
fixed a typo that caused test failure. plz relaunch test, thx~ @jeffra @tjruwase

**Review by cmikeh2 — APPROVED** [review]
Thanks for this PR! Looks we just had some breaking changes in the softmax kernel, but once we can merge cleanly this all looks good to me.

**Comment by dc3671** [comment]
@cmikeh2 The conflict is fixed. Could you relaunch the workflow? Thanks.

**Comment by dc3671** [comment]
@cmikeh2 Sry, I just fixed some problems of template declaration in softmax.cu. Please relaunch workflow, thanks~

**Comment by dc3671** [comment]
@cmikeh2 @tjruwase @jeffra please relaunch workflow, thanks~

**Comment by dc3671** [comment]
@cmikeh2 @tjruwase @jeffra The conflict is resolved. Hope it can be merged successfully this time🤣

**Comment by dc3671** [comment]
@cmikeh2 @tjruwase @jeffra the amd test workflow(https://github.com/microsoft/DeepSpeed/actions/runs/4673912327) failed, but I don't it's related to my modification... And again I rebased master branch, could you please relaunch the workflow? Thanks~

**Comment by dc3671** [comment]
@cmikeh2 the nv-mii test and amd test failed again. Do you think it's related to my modification? Or just need to retry?

**Comment by cmikeh2** [comment]
> @cmikeh2 the nv-mii test and amd test failed again. Do you think it's related to my modification? Or just need to retry?

I think it’s likely unrelated. We sometimes see node issues with the MII tests and the AMD tests seem to be failing elsewhere as well. I’ll investigate this internally and see what we can do to get this merged in.

**Comment by dc3671** [comment]
@cmikeh2 @tjruwase @jeffra gentle ping 🤷‍♂️

**Comment by dc3671** [comment]
@cmikeh2 @tjruwase @jeffra gentle ping

**Comment by dc3671** [comment]
@cmikeh2 @tjruwase @jeffra  A fix of cupy installation(https://github.com/microsoft/DeepSpeed/pull/3276) is synced from master. Please relaunch workflow. Thanks

**Comment by dc3671** [comment]
@cmikeh2 @tjruwase @jeffra hi, is amd-mi200 test unable to launch? I see many actions are pending on this workflow.

**Comment by tjruwase** [comment]
@dc3671, yes, we are not having much luck with this workflow.

**Pull request merged**
