### PR TITLE
fix [BUG] 'DeepSpeedGPTInference' object has no attribute 'dtype' for…

### PR DESCRIPTION
**Pull request by jxysoft**
… int8 inference #4813

### CODE REVIEW

**Comment by jxysoft** [comment]
who can help me to review the pr? it's an easy finding bug

**Review by cmikeh2 — APPROVED** [review]

**Comment by jxysoft** [comment]
who knows why the 3 units test failed?  caused by my code?

**Comment by tjruwase** [comment]
> who knows why the 3 units test failed? caused by my code?

@jxysoft, I think it is a problem with our CI. We are taking a look!

**Review by mrwyattii — APPROVED** [review]

**Comment by kiucho** [comment]
Does deepspeed support INT8 inference?

**Pull request merged**
