### PR TITLE
Don't check overflow for bf16 data type

### PR DESCRIPTION
**Pull request by hablb**
Always check for fp16
bf16 dynamic range is similar to fp32. don't check overflow by default.

### CODE REVIEW

**Comment by tjruwase** [comment]
@hablb, thanks for the PR. While I understand restricting overflow checks to fp16 only, I don't see the benefit of providing a config option to enable overflow checks for bf16/fp32. Can you please explain the need for the config option? I think the restriction part is fine.

**Comment by hablb** [comment]
Thanks @tjruwase 
I removed the configuration variable. Just skipping overflow check for fp16 now.

**Review by tjruwase — APPROVED** [review]

**Comment by jinzhuer** [comment]
Dear @hablb ,Besides wasting computational resources, are there any other downsides to performing overflow checks on bf16 data types? Would performing overflow checks on bf16 data types cause any other bugs?

**Comment by hablb** [comment]
No other downsides, however this check significant overhead as it reduces all gradients, communicates and synchronizes with the cpu.

**Pull request merged**
