### PR TITLE
Update offload parameter names

### PR DESCRIPTION
**Pull request by tjruwase**
Update configuration names for [parameter offloading](https://www.deepspeed.ai/docs/config-json/#parameter-offloading) and [optimizer offloading](https://www.deepspeed.ai/docs/config-json/#optimizer-offloading). 

@stas00, FYI

### CODE REVIEW

**Comment by stas00** [comment]
Thank you for working on that, @tjruwase - the code that it documents needs to be updated too to print the correct config options in its reports (both z2 and z3).

**Comment by tjruwase** [comment]
@stas00, please see the new output below:

For zero 2
```bash
Estimated memory needed for params, optim states and gradients for a:
HW: Setup with 1 node, 8 GPUs per node.
SW: Model with 2851M total params.
  per CPU  |  per GPU |   Options
  127.48GB |   5.31GB | {'offload_optimizer': {'device': 'cpu'}}
  127.48GB |  15.93GB | {'offload_optimizer': {'device': 'none'}}
```

For zero 3
```bash
Estimated memory needed for params, optim states and gradients for a:
HW: Setup with 1 node, 8 GPUs per node.
SW: Model with 2851M total params, 32M largest layer params.
  per CPU  |  per GPU |   Options
   71.71GB |   0.12GB | {'offload_param': {'device': 'cpu'}, 'offload_optimizer': {'device': 'cpu'}}, zero_init=1
  127.48GB |   0.12GB | {'offload_param': {'device': 'cpu'}, 'offload_optimizer': {'device': 'cpu'}}, zero_init=0
   63.74GB |   0.79GB | {'offload_param': {'device': 'none'}, 'offload_optimizer': {'device': 'cpu'}}, zero_init=1
  127.48GB |   0.79GB | {'offload_param': {'device': 'none'}, 'offload_optimizer': {'device': 'cpu'}}, zero_init=0
    1.47GB |   6.10GB | {'offload_param': {'device': 'none'}, 'offload_optimizer': {'device': 'none'}}, zero_init=1
  127.48GB |   6.10GB | {'offload_param': {'device': 'none'}, 'offload_optimizer': {'device': 'none'}}, zero_init=0
```

Please let me know if the wrapper `{` `}` around the `offload_*` parameters is a problem and I will try to tweak the formatting to get rid off. 

Also, I notice that for zero 2 the per CPU memory usage is the same with offload and without offload. But I can't think of the cause of the CPU memory usage without offload.

**Comment by stas00** [comment]
Definitely let's get rid of all those bracket, quotes and useless info. I propose:

```
Estimated memory needed for params, optim states and gradients for a:
HW: Setup with 1 node, 8 GPUs per node.
SW: Model with 2851M total params.
  per CPU  |  per GPU |   Options
  127.48GB |   5.31GB | offload_optimizer=cpu
  127.48GB |  15.93GB | offload_optimizer=none

Estimated memory needed for params, optim states and gradients for a:
HW: Setup with 1 node, 8 GPUs per node.
SW: Model with 2851M total params, 32M largest layer params.
  per CPU  |  per GPU |   Options
   71.71GB |   0.12GB | offload_param=cpu,  offload_optimizer=cpu,  zero_init=1
  127.48GB |   0.12GB | offload_param=cpu,  offload_optimizer=cpu,  zero_init=0
   63.74GB |   0.79GB | offload_param=none, offload_optimizer=cpu,  zero_init=1
  127.48GB |   0.79GB | offload_param=none, offload_optimizer=cpu,  zero_init=0
    1.47GB |   6.10GB | offload_param=none, offload_optimizer=none, zero_init=1
  127.48GB |   6.10GB | offload_param=none, offload_optimizer=none, zero_init=0
```

**Comment by stas00** [comment]
> Also, I notice that for zero 2 the per CPU memory usage is the same with offload and without offload. But I can't think of the cause of the CPU memory usage without offload.

It's dependent on the number of gpus in the requested config:

https://github.com/microsoft/DeepSpeed/blob/bd3ebddf3628f3f77d3460e49626c8af7825a92c/deepspeed/runtime/zero/stage2.py#L2168-L2173

**Comment by stas00** [comment]
And then there was NVME, but that's a different project.

**Comment by tjruwase** [comment]
> It's dependent on the number of gpus and nodes in the requested config:

Hmm, let's chat more about this. It seems I am missing some context.

**Comment by tjruwase** [comment]
@stas00, please see new output below. I padded cpu, so the `,` looks a bit odd. What do you think?
```bash
Estimated memory needed for params, optim states and gradients for a:
HW: Setup with 1 node, 8 GPUs per node.
SW: Model with 2851M total params.
  per CPU  |  per GPU |   Options
  127.48GB |   5.31GB | offload_optimizer=cpu
  127.48GB |  15.93GB | offload_optimizer=none

HW: Setup with 1 node, 8 GPUs per node.
SW: Model with 2851M total params, 32M largest layer params.
  per CPU  |  per GPU |   Options
   71.69GB |   0.12GB | offload_param=cpu , offload_optimizer=cpu , zero_init=1
  127.45GB |   0.12GB | offload_param=cpu , offload_optimizer=cpu , zero_init=0
   63.72GB |   0.78GB | offload_param=none, offload_optimizer=cpu , zero_init=1
  127.45GB |   0.78GB | offload_param=none, offload_optimizer=cpu , zero_init=0
    1.43GB |   6.09GB | offload_param=none, offload_optimizer=none, zero_init=1
  127.45GB |   6.09GB | offload_param=none, offload_optimizer=none, zero_init=0
```

**Comment by stas00** [comment]
The format looks great to me, @tjruwase! Thank you!

> > It's dependent on the number of gpus and nodes in the requested config:
> 
> Hmm, let's chat more about this. It seems I am missing some context.

Ask and you shall receive ;) 

I am not sure what you're missing, but if you clarify it'd help.

**Comment by tjruwase** [comment]
> I am not sure what you're missing, but if you clarify it'd help.

My expectation is that there should no cpu mem (or cycle) usage for zero2 and zero3 without any offload. Compute should only be in GPU, while params/gradients and optimizer should be only in GPU memory. The only exception would be activation checkpointing to cpu memory, but I didn't think that is included in this estimation. So what am I forgetting? :)

**Comment by stas00** [comment]
You're forgetting the loading stage.

ZeRO-3 has `zero.Init` which can bypass CPU and load directly to gpu.

ZeRO-2 doesn't have it, so everything has to be loaded first onto CPU memory and then transferred to GPU.

**Comment by tjruwase** [comment]
> You're forgetting the loading stage.
> 
> ZeRO-3 has `zero.Init` which can bypass CPU and load directly to gpu.
> 
> ZeRO-2 doesn't have it, so everything has to be loaded first onto CPU memory and then transferred to GPU.

Aha! I knew I was missing something. Thanks.

**Review by jeffra — APPROVED** [review]

**Pull request merged**
