### PR TITLE
Fix #2096 - MoELayer accepts varient in out dim

### LINKED ISSUE #2096: Why the MoE layer forces the input hidden dimenstion the same as the output hidden dimension?
image
I notice a problem when I read the [tutorial](https://www.deepspeed.ai/tutorials/mixture-of-experts/) of MoE. As the figure shows, it says the input dimension must be equal to the output dimension. This absolutely imports complexity for many DNNs, and I don't understand why this is necessary. In my view, the output dimension is supposed to be easily set at will?

### PR DESCRIPTION
**Pull request by mhjabreel**

### CODE REVIEW

**Comment by awan-10** [comment]
Thank you for this PR @mhjabreel.

@ykim362 -- can you please review it? This looks good to me.

**Comment by ykim362** [comment]
@awan-10 
The changes look good to me!

**Comment by awan-10** [comment]
Thank you @ykim362 for your review! Let me approve and run tests.

**Review by awan-10 — APPROVED** [review]
Thanks for the PR @mhjabreel!

**Pull request closed without merging**
