### PR TITLE
aio: enable -O3 optimization

### PR DESCRIPTION
**Pull request by adammoody**
This updates the aio op to build with ``-O3`` rather than ``-O0`` optimization.

It looks like all ops either build with ``-O2`` or ``-O3``, but aio uses ``-O0`` for some reason.  Is that intentional?

### CODE REVIEW

**Comment by tjruwase** [comment]
@adammoody, aio op is IO-bound and thus gets little benefit from compiler optimizations. So we choose `-O0` for better debugging experience.

**Comment by adammoody** [comment]
Ok, thanks.  I had noticed that some of aio includes some SIMD code like here:

https://github.com/microsoft/DeepSpeed/blob/6ba96289702afc56948aa9f6cff55d7df678ccc0/csrc/aio/py_lib/deepspeed_py_copy.cpp#L107-L109

On PowerPC, those SIMD-tuned algorithms aren't available, so it falls back to the non-vectorized copy method here:

https://github.com/microsoft/DeepSpeed/blob/6ba96289702afc56948aa9f6cff55d7df678ccc0/csrc/aio/py_lib/deepspeed_py_copy.cpp#L46-L49

I thought the compiler might help in that case, and that maybe that would be useful since someone took the time to create the SIMD versions.

I do understand performance being bound by much slower I/O, though.

Mind if I replace this PR with one that adds a comment to note why ``-O0`` is used?

**Comment by tjruwase** [comment]
> Ok, thanks. I had noticed that some of aio includes some SIMD code like here:

Yes, you are correct. That was a failed attempt to create fast copy routines, but was abandoned due to poor progress. The routines are currently not used, and these codes should be ideally be deleted. Sorry for the confusion.

**Comment by tjruwase** [comment]
> Mind if I replace this PR with one that adds a comment to note why `-O0` is used?

Thanks, that would be very much appreciated.

**Review by tjruwase — APPROVED** [review]

**Pull request merged**
