### PR TITLE
Enable mixtral 8x7b autotp

### PR DESCRIPTION
**Pull request by Yejing-Lai**
This PR aims to enable mixtral 8x7b (MoE model) autotp.

### CODE REVIEW

**Comment by Yejing-Lai** [comment]
Hi @mrwyattii @delock. Please kindly review. Thanks!

**Comment by loadams** [comment]
> Hi @mrwyattii @delock. Please kindly review. Thanks!

@delock - do we want this merged in after your CPU autoTP PR?

**Comment by delock** [comment]
> > Hi @mrwyattii @delock. Please kindly review. Thanks!
> 
> @delock - do we want this merged in after your CPU autoTP PR?

Hi @loadams , this can be merged before CPU autoTP workflow PR.  I'll keep on working on that PR.

**Review by mrwyattii — APPROVED** [review]

**Review by loadams — APPROVED** [review]

**Comment by Yejing-Lai** [comment]
Hi @loadams. From the failure log it seems an env issue. Could you run the CI again to check if env issue?

**Comment by loadams** [comment]
> Hi @loadams. From the failure log it seems an env issue. Could you run the CI again to check if env issue?

Hi @Yejing-Lai - yes we have a known env issue that we are working to resolve and will merge this PR when fixed.

**Pull request merged**
