### PR TITLE
fixing the dataloader original len issue

### PR DESCRIPTION
**Pull request by tomekrut**
This is related to issue https://github.com/microsoft/DeepSpeed/issues/176

### CODE REVIEW

**Comment by tjruwase** [comment]
Thanks! This is looks great. 
Can you please add some unit tests? To cover
1) Batch mode
2) Non-batch mode
3) Multiple epochs

**Comment by jeffra** [comment]
@tomekrut are you able to sign the contributor license agreement? Would love to merge your contribution soon! :)

**Comment by tomekrut** [comment]
> @tomekrut are you able to sign the contributor license agreement? Would love to merge your contribution soon! :)

Hi @jeffra - are you ok with that? Do you write unit test for things like that as well? If so, I can look at it but most likely Friday / Monday.

**Comment by rocm-mici** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
