### PR TITLE
Allow DeepSpeed models to be initialized with optimizer=None

### PR DESCRIPTION
**Pull request by gcooper-isi**
The optimizer uses quite a bit of GPU memory. For training, this is necessary, but not for simply running the model. Therefore, allowing `optimizer` to be set to `None` can dramatically reduce GPU memory usage when running the model. However, in the current version of the code, doing so will cause an exception to be thrown.

### CODE REVIEW

**Comment by ShadenSmith** [comment]
Hi @gcooper-isi , thanks for this contribution! I pushed a small commit that adds a unit test and also avoids an issue when no optimizer is specified in the JSON configuration.

If you haven't yet, can you sign the CLA from the above bot? We will need it before merging.

**Comment by gcooper-isi** [comment]
Thanks so much for adding the unit test! I have asked my employer for permission to sign the CLA, which I don't expect to be an issue, and I will sign it as soon as they say it's OK.

**Comment by jeffra** [comment]
@gcooper-isi just wanted to bump this back up. Okay to sign the CLA?

**Comment by gcooper-isi** [comment]
> @gcooper-isi just wanted to bump this back up. Okay to sign the CLA?

I'm OK to sign it personally, but since this requires permission from my company it has had to work its way through the various levels of bureaucracy before they finish the approval. I keep getting periodic updates that it has made it through each next step and I'll continue to follow up.

**Comment by gcooper-isi** [comment]
> > @gcooper-isi just wanted to bump this back up. Okay to sign the CLA?
> 
> I'm OK to sign it personally, but since this requires permission from my company it has had to work its way through the various levels of bureaucracy before they finish the approval. I keep getting periodic updates that it has made it through each next step and I'll continue to follow up.

As far as my contracts team is concerned, though, I don't have a deadline for signing this contract. If you can provide any information that could help convince them that doing this in a timely way would be important, that may help speed things along.

**Comment by jeffra** [comment]
> > > @gcooper-isi just wanted to bump this back up. Okay to sign the CLA?
> > 
> > 
> > I'm OK to sign it personally, but since this requires permission from my company it has had to work its way through the various levels of bureaucracy before they finish the approval. I keep getting periodic updates that it has made it through each next step and I'll continue to follow up.
> 
> As far as my contracts team is concerned, though, I don't have a deadline for signing this contract. If you can provide any information that could help convince them that doing this in a timely way would be important, that may help speed things along.

@gcooper-isi DeepSpeed is updating at a rapid pace. You might tell them that if they are too slow the risk is that your contributions might be too out of date to be successfully merged. We all see value in your contributions, so I hope they agree soon. The CLA as far as I understand shouldn’t be too controversial for this type of commit, but of course I’m not a lawyer :)

**Comment by gcooper-isi** [comment]
I finally got permission from my employer to sign the CLA and have done so. Please let me know if there is anything else I can do.

**Review by ShadenSmith — APPROVED** [review]

**Review by jeffra — APPROVED** [review]

**Pull request merged**
