### PR TITLE
checking process_group before merging bucket ranges (#3521)

### LINKED ISSUE #3521: [BUG] average_tensor coalesing does not take process_group into consideration for MoE
**Describe the bug**
When decision about coalescing adjacent tensors is made right now it is currently only based on `partition_id` [here](https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/runtime/zero/stage_1_and_2.py#L923) which is simply target's rank in the `range(dist.get_world_size(group=process_group))`. This means that even though expert data parallel and data parallel both have `partition_id=0` they could belong to different physical ranks in different `process_group`s.

**To Reproduce**
A unit test will be added soon.

**Expected behavior**
`stage_1_and_2`'s `average_tensor` should detect `param_group`s belong to different `process_group`s, e.g. by remembering `prev_process_group`.

**ds_report output**
```
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-devel package with yum
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  using untested triton version (2.0.0), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
utils .................. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/home/azzhipa/.local/lib/python3.9/site-packages/torch']
torch version .................... 1.13.1+cu116
deepspeed install path ........... ['/home/azzhipa/workspace/DeepSpeed/deepspeed']
deepspeed info ................... 0.9.2+f7d71ec1, f7d71ec1, HEAD
torch cuda version ............... 11.6
torch hip version ................ None
nvcc version ..................... 11.6
deepspeed wheel compiled w. ...... torch 1.12, cuda 11.6
```

**Screenshots**
N/A

**System info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - GPU count and types: 1 machine with 8x A100s
 - Interconnects (if applicable) 4x 100 Gbps AWS EFA adaptors
 - Python version: 3.9
 - Any other relevant info about your setup: N/A

**Launcher context**
Launching with `deepspeed` runner

**Docker context**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by clumsy**
A simple check to make sure we compare `partition_id`s for the same `process_group`.

Fix #3521

### CODE REVIEW

**Comment by tjruwase** [comment]
@clumsy, thanks for the PR. It looks good. But I am curious if this caused some failure? Also, can you add a unit test for this? T

**Comment by tjruwase** [comment]
Never mind, I just saw the issue. Looking forward to the unit test. Thanks!

**Comment by clumsy** [comment]
Sure thing, @tjruwase, I was just able to reproduce this in a unit test with ZeRO2 `world_size = ep_size = 4`:
```
i=1 param_id=16 partition_id=0 prev_id=0 MoE:ep_size_4 pg_size=1 pg=0x7f20ac780530>
^-COALESCING-v
i=0 param_id=1 partition_id=0 prev_id=0 dense pg_size=4 pg=0x7f20ac780670>
```
Now I just need to put a proper assertion and I'll update the PR. Looks like in this case it's going to be a partially reduced gradients for dense parameters.

**Comment by clumsy** [comment]
Sorry not the prettiest of unit tests, @tjruwase. But it's the most robust one I was able to come up with: if we ever clamp together partitions for different `process_group`s using `Tensor.narrow()` inside `average_tensor()` this test will fail.

Before fix:
```
FAILED tests/unit/moe/test_moe.py::TestMoE::test[True-2-2]
FAILED tests/unit/moe/test_moe.py::TestMoE::test[True-2-4]
============================================================================================= 2 failed, 10 passed, 2 deselected, 6 warnings in 162.20s (0:02:42) ==============================================================================================
```

After fix:
```
14.73s call     unit/moe/test_moe.py::TestMoE::test[True-2-4]
14.27s call     unit/moe/test_moe.py::TestMoE::test[False-2-4]
14.16s call     unit/moe/test_moe.py::TestMoE::test[False-2-2]
14.07s call     unit/moe/test_moe.py::TestMoE::test[False-1-4]
13.90s call     unit/moe/test_moe.py::TestMoE::test[True-0-2]
13.59s call     unit/moe/test_moe.py::TestMoE::test[True-0-4]
13.31s call     unit/moe/test_moe.py::TestMoE::test[False-1-2]
13.09s call     unit/moe/test_moe.py::TestMoE::test[True-1-4]
12.84s call     unit/moe/test_moe.py::TestMoE::test[False-0-4]
12.58s call     unit/moe/test_moe.py::TestMoE::test[True-2-2]
12.57s call     unit/moe/test_moe.py::TestMoE::test[True-1-2]
12.45s call     unit/moe/test_moe.py::TestMoE::test[False-0-2]

(24 durations < 1s hidden.  Use -vv to show these durations.)
================================================================================================== 12 passed, 2 deselected, 6 warnings in 162.79s (0:02:42) ===================================================================================================
```

**Review by tjruwase — APPROVED** [review]

**Comment by clumsy** [comment]
Closing since the fix has been merged to `master` branch. Please correct me if I'm wrong, @tjruwase.

**Comment by tjruwase** [comment]
@clumsy, I don't believe this was merged. Can you please point me to merged PR? Thanks!

**Pull request closed without merging**
