### PR TITLE
Fix crash when creating Torch tensor on NPU with device=get_accelerator().current_device()

### PR DESCRIPTION
**Pull request by harygo2**
Creating a Torch tensor with the parameter `device=get_accelerator().current_device()` can result in a crash when using an NPU. 

This issue arises because the `current_device` API across all accelerators is expected to return a device id as an integer, according to the [interface docs.](https://github.com/microsoft/DeepSpeed/blob/fa8458b1a80d6ba55091b17f092de19bbf95eb3d/docs/_tutorials/accelerator-abstraction-interface.md?plain=1#L52C1-L56C103) 

However, specifying `device` as an interger when creating tensors by default directs Torch to use the CUDA backend, which leads to crash on NPUs (and potentially other accelerators as well).

To resolve this, we should use `get_accelerator().current_device_name()` instead, which returns the correct device identifier strings such as `"npu:0", "cuda:0", or "xpu:0"`. This API provides the appropriate context needed for creating tensors on specific hardware accelerators.

I also notice that  `device=get_accelerator().current_device()` is used across several files under deepspeed/inference, and may also lead to crash on other accelerators.

### CODE REVIEW

**Comment by minchao-sun** [comment]
Hi, @tjruwase . Would you please review this PR?

BTW, this issue happened before. See https://github.com/microsoft/DeepSpeed/pull/3933.

**Comment by tjruwase** [comment]
[like]  Olatunji Ruwase reacted to your message:
________________________________

**Review by tjruwase — APPROVED** [review]

**Comment by harygo2** [comment]
Hi, @tjruwase. Just fix a formatting issue in new commit. Would you please approve the workflows to run?

**Comment by harygo2** [comment]
Hi, @tjruwase, the nv-accelerate-v100 and nv-lightening-v100 CI workflows seems to be down.
image
image

Could you please take a look? Thx.

**Comment by delock** [comment]
I did a search for `current_device()` in DeepSpeed repo and it looks like most occurance of `current_device()` should be `current_device_name()` in order to be compatible to non-cuda device.  Maybe increase test coverage on non-cuda device would help catch such usage in the future.

**Comment by harygo2** [comment]
Hi, @tjruwase @loadams, All checks have passed, could you add this PR to the merge queue?

**Comment by harygo2** [comment]
Hi, @tjruwase, this PR was removed from merge queue by the bot, not sure why it was removed, could you please check it out?

**Comment by loadams** [comment]
> Hi, @tjruwase, this PR was removed from merge queue by the bot, not sure why it was removed, could you please check it out?

Hi @harygo2 - looks like a transient failure on the merge queue system, I'll re-queue.

**Pull request merged**
