### PR TITLE
[Fix] _conv_flops_compute when padding is a str and stride=1

### PR DESCRIPTION
**Pull request by zhiruiluo**
The _conv_flops_compute wasn't supporting the case when padding is either 'valid' or 'same' when stride=1.
This PR adds the support for this.

### CODE REVIEW

**Comment by zhiruiluo** [comment]
@microsoft-github-policy-service agree

> @zhiruiluo please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Review by cli99 — APPROVED** [review]
thanks for the PR!

**Comment by zhiruiluo** [comment]
Hi @cli99 Regrettably, a test failure occurred during the pip building phase. However, based on my analysis, it appears that this issue is not related to the changes made in this pull request. Therefore, I kindly request that the necessary checks be approved to run once again.

**Comment by zhiruiluo** [comment]
Hi @cli99, I have applied pre-commit checks which caused the only failure in the test.

**Comment by zhiruiluo** [comment]
Hi @cli99 @tjruwase. I believe this is good to merge into master. Could you guys find a time to merge this PR?

**Pull request merged**
