### PR TITLE
fix fused_qkv model accuracy issue

### PR DESCRIPTION
**Pull request by Yejing-Lai**
Fused_qkv model can not correctly choose the fused_qkv type. Need to update the module_name_matches.

### CODE REVIEW

**Comment by Yejing-Lai** [comment]
Hi @mrwyattii @delock. Please kindly review, Thanks!

**Comment by delock** [comment]
@Yejing-Lai  what specific value of `module_str` and `k` caused the issue?

**Comment by Yejing-Lai** [comment]
> @Yejing-Lai what specific value of `module_str` and `k` caused the issue?
It is a logic error. The _k_ is contained in _module_str_. The module_name_matches cannot get the correct fused_type now. This will cause all models to choose bloom_type.

**Comment by delock** [comment]
`if k in module_str` does it mean `k` is a substring of `module_str` or `k` is an element of `module_str` as a list?

**Comment by Yejing-Lai** [comment]
> `if k in module_str` does it mean `k` is a substring of `module_str` or `k` is an element of `module_str` as a list?
Yes.

**Comment by Yejing-Lai** [comment]
For example:
k = "CodeGenBlock"
module_str="
(module): CodeGenForCausalLM(
    (transformer): CodeGenModel(
      (wte): Embedding(51200, 2560)
      (drop): Dropout(p=0.0, inplace=False)
      (h): ModuleList(
        (0-31): 32 x **CodeGenBlock**(
          (ln_1): LayerNorm((2560,), eps=1e-05, elementwise_affine=True)
          (attn): CodeGenAttention(
            (attn_dropout): Dropout(p=0.0, inplace=False)
            (resid_dropout): Dropout(p=0.0, inplace=False)
            (qkv_proj): LinearLayer()
            (out_proj): LinearAllreduce()
          )
          (mlp): CodeGenMLP(
            (fc_in): LinearLayer()
            (fc_out): LinearAllreduce()
            (act): NewGELUActivation()
            (dropout): Dropout(p=0.0, inplace=False)
          )
        )
      )
      (ln_f): LayerNorm((2560,), eps=1e-05, elementwise_affine=True)
    )
    (lm_head): LmHeadLinearAllreduce()
  )
"
We need to judge ` if k in module_str` rather than `module_str in k`.
Thanks.

**Comment by delock** [comment]
Hi @mrwyattii can you help review this PR?   This PR fixed an accuracy issue for various models with fused qkv.  i.e. Baichuan, code gen, bloom, mpt.

**Review by tjruwase — APPROVED** [review]

**Pull request merged**
