### PR TITLE
fix llama meta data error and LLaMa lm_head wrongly loading error

### PR DESCRIPTION
**Pull request by baodii**
* fix 'NotImplementedError: Cannot copy out of meta tensor; no data!', when loading LLaMa from device meta

### CODE REVIEW

**Comment by baodii** [comment]
@delock @guoyejun @rogerxfeng8

**Comment by mpjlu** [comment]
master llama container doesn't support meta tensor,  this this PR still cannot work

**Comment by baodii** [comment]
> 

This PR is used with autoTP, not kernel injection. It will work when the model you put in init_inference API is meta device.

**Comment by baodii** [comment]
> master llama container doesn't support meta tensor, this this PR still cannot work

This PR is used with autoTP, not kernel injection. It will work when the model you put in init_inference API is meta device.

**Comment by xs1997zju** [comment]
appreciate for this pr

**Comment by puneeshkhanna** [comment]
When will this merge ?

**Review by cmikeh2 — APPROVED** [review]
Thank you!

**Comment by baodii** [comment]
resolved conflict.

**Pull request closed without merging**
