### PR TITLE
Port Reza's INT8-quantization fix to container architecture

### PR DESCRIPTION
**Pull request by lekurile**
This PR ports @RezaYazdaniAminabadi's INT8-quantization fix for BLOOM, OPT, and Neo-X (GH-2662) to the refactored "containers" architecture.

### CODE REVIEW

**Review by RezaYazdaniAminabadi — APPROVED** [review]
All LGTM, thanks @lekurile and @HeyangQin :)

**Review by lanking520 — COMMENTED** [review]
Thanks for the contribution. Much appreciated!

**Comment by sindhuvahinis** [comment]
I am getting this error while trying to test your PR. Is this any version mismatch?

**Comment by lekurile** [comment]
> I am getting this error while trying to test your PR. Is this any version mismatch?
> 
> ```
> Traceback (most recent call last):
>   File "inference-test.py", line 57, in <module>
>     pipe.model = deepspeed.init_inference(pipe.model,
>   File "/usr/local/lib/python3.8/dist-packages/deepspeed/__init__.py", line 311, in init_inference
>     _, layer_id = _replace_module(child, policies, layer_id=layer_id)
>   File "/usr/local/lib/python3.8/dist-packages/deepspeed/module_inject/replace_module.py", line 822, in _replace_module
>     engine = InferenceEngine(model, config=ds_inference_config)
>   File "/usr/local/lib/python3.8/dist-packages/deepspeed/inference/engine.py", line 128, in __init__
>     self._apply_injection_policy(config)
>   File "/usr/local/lib/python3.8/dist-packages/deepspeed/inference/engine.py", line 351, in _apply_injection_policy
>     _, layer_id = _replace_module(child, policies, layer_id=layer_id)
>   File "/usr/local/lib/python3.8/dist-packages/deepspeed/module_inject/replace_module.py", line 812, in _replace_module
>     replace_transformer_layer(client_module,
>   File "/usr/local/lib/python3.8/dist-packages/deepspeed/module_inject/replace_module.py", line 530, in replace_transformer_layer
>     replaced_module = replace_module(model=model,
>   File "/usr/local/lib/python3.8/dist-packages/deepspeed/module_inject/replace_module.py", line 795, in replace_module
>     replaced_module = policies[child.__class__][0](child,
>   File "/usr/local/lib/python3.8/dist-packages/deepspeed/module_inject/replace_module.py", line 520, in replace_fn
>     replaced_module, _ = _replace_module(model, policy)
>   File "/usr/local/lib/python3.8/dist-packages/deepspeed/module_inject/replace_module.py", line 822, in _replace_module
>     new_module = replace_with_policy(child,
>   File "/usr/local/lib/python3.8/dist-packages/deepspeed/module_inject/replace_module.py", line 383, in replace_with_policy
>     _container.create_module()
> _, layer_id = _replace_module(child, policies, layer_id=layer_id)
>   File "/usr/local/lib/python3.8/dist-packages/deepspeed/module_inject/containers/gptj.py", line 20, in create_module
>   File "/usr/local/lib/python3.8/dist-packages/deepspeed/module_inject/replace_module.py", line 822, in _replace_module
>     self.module = DeepSpeedGPTInference(_config, mp_group=self.mp_group)
>   File "/usr/local/lib/python3.8/dist-packages/deepspeed/model_implementations/transformers/ds_gpt.py", line 18, in __init__
>     super().__init__(config,
>   File "/usr/local/lib/python3.8/dist-packages/deepspeed/model_implementations/transformers/ds_transformer.py", line 52, in __init__
>     _, layer_id = _replace_module(child, policies, layer_id=layer_id)
>   File "/usr/local/lib/python3.8/dist-packages/deepspeed/module_inject/replace_module.py", line 812, in _replace_module
>     builder = InferenceBuilder()
> TypeError: 'str' object is not callable
> ```

Can you please try checking out the `lekurile/container_int8_fix` branch and reinstalling DeepSpeed locally?

Something like:
```
git pull
git checkout lekurile/container_int8_fix
git clean -fdx
pip uninstall deepspeed
pip install -e .
```

**Comment by sindhuvahinis** [comment]
@lekurile  git clean made it work. Thanks.
But  it does not work for gpt-neox-20b for both fp16 and int8

To reproduce, used your [test-suite](https://github.com/microsoft/DeepSpeedExamples/blob/master/inference/huggingface/text-generation/inference-test.py)

**Comment by lekurile** [comment]
> @lekurile git clean made it work. Thanks. But it does not work for gpt-neox-20b for both fp16 and int8
> 
> To reproduce, used your [test-suite](https://github.com/microsoft/DeepSpeedExamples/blob/master/inference/huggingface/text-generation/inference-test.py)
> 
> ```
> deepspeed --num_nodes 1    \
>  --num_gpus 4     \
> inference-test.py     \
> --use_kernel     \
> --use_meta_tensor     \
> --ds_inference     \
> --name EleutherAI/gpt-neox-20b  \
> --replace_method auto   \
> --checkpoint_path /tmp/ws/gpt-neox-20b/
> ```
> 
> Getting the error below:
> 
> ```
> Traceback (most recent call last):
>   File "inference-test.py", line 57, in <module>
>     pipe.model = deepspeed.init_inference(pipe.model,
>   File "/tmp/ws/DeepSpeed/deepspeed/__init__.py", line 311, in init_inference
>     engine = InferenceEngine(model, config=ds_inference_config)
>   File "/tmp/ws/DeepSpeed/deepspeed/inference/engine.py", line 140, in __init__
>     self.module.to(device)
>   File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 927, in to
>     return self._apply(convert)
>   File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 579, in _apply
>     module._apply(fn)
>   File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 579, in _apply
>     module._apply(fn)
>   File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 602, in _apply
>     param_applied = fn(param)
>   File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 925, in convert
>     return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
> NotImplementedError: Cannot copy out of meta tensor; no data!
> ```

Glad git clean unblocked that issue.

We're currently actively investigating the load checkpoint functionality across the models for which this feature has been implemented. Please refer to the issue here https://github.com/microsoft/DeepSpeed/issues/2770 for further details. Thanks, Lev.

**Comment by sindhuvahinis** [comment]
> Glad git clean unblocked that issue.
> 
> We're currently actively investigating the load checkpoint functionality across the models for which this feature has been implemented. Please refer to the issue here #2770 for further details. Thanks, Lev.

@lekurile Thank you for your reply. Yes I understand, I created that issue. 

Trying to understand, what does this PR fix then? Does it work for int8 quantization of gpt-neox-20b without checkpoint loading? You mean directly downloading from huggingface hub without checkpoint and meta tensors?

**Comment by panx27** [comment]
Thanks a lot for the effort! When I try to use the [test-suite](https://github.com/microsoft/DeepSpeedExamples/blob/master/inference/huggingface/text-generation/inference-test.py) to load BLOOM models (both 560m and 175B). 

`deepspeed --num_nodes 1 --num_gpus 8 inference-test.py --use_kernel --use_meta_tensor --ds_inference  --replace_method auto --name bigscience/bloom-560m --dtype int8`

I got the following error:
```
  File "inference-test.py", line 75, in <module>
    pipe.model = deepspeed.init_inference(pipe.model,
  File "/workspace/code/DeepSpeed/deepspeed/__init__.py", line 311, in init_inference
    engine = InferenceEngine(model, config=ds_inference_config)
  File "/workspace/code/DeepSpeed/deepspeed/inference/engine.py", line 128, in __init__
    self._apply_injection_policy(config)
  File "/workspace/code/DeepSpeed/deepspeed/inference/engine.py", line 351, in _apply_injection_policy
    replace_transformer_layer(client_module,
  File "/workspace/code/DeepSpeed/deepspeed/module_inject/replace_module.py", line 559, in replace_transformer_layer
    load_model_with_checkpoint(replaced_module,
  File "/workspace/code/DeepSpeed/deepspeed/module_inject/load_checkpoint.py", line 279, in load_model_with_checkpoint
    load_module_recursive(r_module)
  File "/workspace/code/DeepSpeed/deepspeed/module_inject/load_checkpoint.py", line 273, in load_module_recursive
    load_module_recursive(
  File "/workspace/code/DeepSpeed/deepspeed/module_inject/load_checkpoint.py", line 273, in load_module_recursive
Traceback (most recent call last):
  File "inference-test.py", line 75, in <module>
    load_module_recursive(
  File "/workspace/code/DeepSpeed/deepspeed/module_inject/load_checkpoint.py", line 271, in load_module_recursive
    layer_policies[child.__class__](child, prefix + name + '.')
  File "/workspace/code/DeepSpeed/deepspeed/module_inject/load_checkpoint.py", line 200, in load_transformer_layer
    replace_policy.load_params(module,
    AttributeErrorpipe.model = deepspeed.init_inference(pipe.model,:
'BLOOMLayerPolicy' object has no attribute 'load_params'  File "/workspace/code/DeepSpeed/deepspeed/__init__.py", line 311, in init_inference
```

deepspeed is built on this branch
version is `0.8.1+803e3761`

**Comment by sindhuvahinis** [comment]
@

> Thanks a lot for the effort! When I try to use the [test-suite](https://github.com/microsoft/DeepSpeedExamples/blob/master/inference/huggingface/text-generation/inference-test.py) to load BLOOM models (both 560m and 175B).
> 
> `deepspeed --num_nodes 1 --num_gpus 8 inference-test.py --use_kernel --use_meta_tensor --ds_inference --replace_method auto --name bigscience/bloom-560m --dtype int8`
> 
> I got the following error:
> 
> ```
>   File "inference-test.py", line 75, in <module>
>     pipe.model = deepspeed.init_inference(pipe.model,
>   File "/workspace/code/DeepSpeed/deepspeed/__init__.py", line 311, in init_inference
>     engine = InferenceEngine(model, config=ds_inference_config)
>   File "/workspace/code/DeepSpeed/deepspeed/inference/engine.py", line 128, in __init__
>     self._apply_injection_policy(config)
>   File "/workspace/code/DeepSpeed/deepspeed/inference/engine.py", line 351, in _apply_injection_policy
>     replace_transformer_layer(client_module,
>   File "/workspace/code/DeepSpeed/deepspeed/module_inject/replace_module.py", line 559, in replace_transformer_layer
>     load_model_with_checkpoint(replaced_module,
>   File "/workspace/code/DeepSpeed/deepspeed/module_inject/load_checkpoint.py", line 279, in load_model_with_checkpoint
>     load_module_recursive(r_module)
>   File "/workspace/code/DeepSpeed/deepspeed/module_inject/load_checkpoint.py", line 273, in load_module_recursive
>     load_module_recursive(
>   File "/workspace/code/DeepSpeed/deepspeed/module_inject/load_checkpoint.py", line 273, in load_module_recursive
> Traceback (most recent call last):
>   File "inference-test.py", line 75, in <module>
>     load_module_recursive(
>   File "/workspace/code/DeepSpeed/deepspeed/module_inject/load_checkpoint.py", line 271, in load_module_recursive
>     layer_policies[child.__class__](child, prefix + name + '.')
>   File "/workspace/code/DeepSpeed/deepspeed/module_inject/load_checkpoint.py", line 200, in load_transformer_layer
>     replace_policy.load_params(module,
>     AttributeErrorpipe.model = deepspeed.init_inference(pipe.model,:
> 'BLOOMLayerPolicy' object has no attribute 'load_params'  File "/workspace/code/DeepSpeed/deepspeed/__init__.py", line 311, in init_inference
> ```
> 
> deepspeed is built on this branch version is `0.8.1+803e3761`
> 
> looks like the load_params() function is in [DS_BloomContainer](https://github.com/microsoft/DeepSpeed/blob/lekurile/container_int8_fix/deepspeed/module_inject/containers/bloom.py#L33)

Try including "parallelization" : "tp" in ds_inference_config.json.

**Pull request merged**
