### PR TITLE
Apex rocm submodule

### PR DESCRIPTION
**Pull request by jithunnair-amd**
This is first of a series of PRs needed to support DeepSpeed on ROCm. This PR adds the ROCm fork of Apex as a git submodule for the DeepSpeed repo and installs the appropriate Apex module.

cc @jeffdaily @sunway513

### CODE REVIEW

**Comment by ShadenSmith** [comment]
Thanks a lot for this and #323. We're excited about supporting more hardware platforms.

We're hard at work and won't be able to review this in detail until next week. In the meantime, do you have suggestions on how we can test AMD support? We ideally would want to be able to cover these code paths in integration testing.

**Comment by ShadenSmith** [comment]
Hi there, sorry for the delay with these. We're internally sorting out some things related to your contributions and will get back to this ASAP.

**Comment by jithunnair-amd** [comment]
Sure, appreciate the circle-back!

**Comment by jithunnair-amd** [comment]
Since apex is not a git submodule of DeepSpeed anymore, closing this PR.

**Pull request closed without merging**
