### PR TITLE
document deepspeed.initialize()

### PR DESCRIPTION
**Pull request by stas00**
As a follow up to the very helpful suggestion I received at https://github.com/microsoft/DeepSpeed/issues/633 I propose this doc update.

Thank you!

Fixes: #633 

@jeffra

### CODE REVIEW

**Review by jeffra — APPROVED** [review]

**Comment by jeffra** [comment]
We currently briefly reference this call related to MPI/AzureML environments (https://www.deepspeed.ai/getting-started/#mpi-and-azureml-compatibility) but thanks for adding it higher up since it seems others will also find this useful.

**Comment by stas00** [comment]
Honestly I'd have never looked there unless I had MPI or Azure ;)

Should I tweak the doc to add that it uses NCCL backend?

**Comment by jeffra** [comment]
Haha totally understandable, it was kind of hidden away it seems :) It also needs to be added to our RTD documentation as well. I'll do that right now actually. You can choose the backend as a parameter, but it does default to NCCL and that's primarily what we've tested everything with across the project. Feel free to add some text about NCCL though.

**Comment by stas00** [comment]
Thank you, @jeffra 

I added the note about the default, but I couldn't find `init_distributed`'s documentation so I couldn't link to it for further details.

**Comment by jeffra** [comment]
Just added it to RTD docs with this PR #645

**Comment by jeffra** [comment]
It's live now at: https://deepspeed.readthedocs.io/en/latest/initialize.html#distributed-initialization

**Comment by stas00** [comment]
That's excellent. Added the link.

**Pull request merged**
