### PR TITLE
[Bug fix] Add rope_theta for llama config

### PR DESCRIPTION
**Pull request by cupertank**
Fixed bug with CodeLlama. Bug description is here https://github.com/microsoft/DeepSpeed/issues/4442. Now DeepSpeed uses rope_theta from transformers.

### CODE REVIEW

**Comment by cupertank** [comment]
@mrwyattii Take a look at this, please.

**Comment by cupertank** [comment]
@mrwyattii, Please, run CI. Do I need to do anything else?

**Review by mrwyattii — APPROVED** [review]

**Comment by mrwyattii** [comment]
Thanks @cupertank LGTM

**Review by lekurile — APPROVED** [review]
Thanks, LGTM!

**Comment by mrwyattii** [comment]
@cupertank it looks like several of the inference related unit tests are failing. I can help debug next week.

**Comment by cupertank** [comment]
@mrwyattii I think I found a bug, run CI, please.

**Comment by cupertank** [comment]
@mrwyattii I hope it's last fix, run CI, please

**Comment by cupertank** [comment]
@mrwyattii I see everything alright now, so maybe we merge it?

**Comment by ryusaeba** [comment]
Do you plan to have a patch release for this?

**Pull request merged**
