### PR TITLE
reduce all-to-all communication volume when both expert and non-expert are tensor-parallel

### PR DESCRIPTION
**Pull request by taozhiwei**
Example: E + M + D parallel
world_size = 8
model_degree = 2
expert_degree = 4 
mp_group = [0, 1], [2,3], [4,5],[6,7]
expert_parallel_group = [0,2,4,6], [1,3,5,7]

The original execution method was that before executing Expert, there was no drop operation, and two EPs did all-to-all separately. In the end, they both obtained complete data, but 0 and 1 obtained exactly the same data. Similarly, 2, 3, and so on all obtained the same data.
Therefore, we can drop the data before executing all-to-all, and then execute allgather after all-to-all to obtain the complete data.

After executing Expert, the data on 0 and 1 is exactly the same, so we can drop it and then execute all-to-all , and then execute allgather to obtain the complete data.

1. non-expert use  TP, expert not use TP: drop -> alltoall -> exe MOE -> alltoall -> allgather
2. both non-expert and expert all use TP: 
   -  the original execution order: alltoall  -> exe MOE-> allreduce -> alltoall
   -  optimized execution order: drop -> alltoall -> allgather -> exe  MOE -> drop ->alltoall -> allgather

### CODE REVIEW

**Comment by tjruwase** [comment]
@siddharth9820, can you help review?

**Comment by siddharth9820** [comment]
At a quick glance, this looks good to me. We did use the same "optimized execution order" in Deepspeed-TED (https://dl.acm.org/doi/pdf/10.1145/3577193.3593704), but I think that update got lost in an unmerged branch. Thank you @taozhiwei for implementing this!

**Comment by taozhiwei** [comment]
> At a quick glance, this looks good to me. We did use the same "optimized execution order" in Deepspeed-TED (https://dl.acm.org/doi/pdf/10.1145/3577193.3593704), but I think that update got lost in an unmerged branch. Thank you @taozhiwei for implementing this!
Thank you for your review,I just updated the mainline code and I need you to perform another test. Thank you.

**Comment by taozhiwei** [comment]
@siddharth9820 Please help review again when you have free time. Thank you very much.

**Comment by taozhiwei** [comment]
@siddharth9820  @tjruwase  Please help review again when you have free time. Thank you very much.

**Comment by siddharth9820** [comment]
@taozhiwei still lgtm. Do you want me to run some tests?

**Comment by taozhiwei** [comment]
> @taozhiwei still lgtm. Do you have some convergence curves for your changes?

I ran a test locally and it still converged

**Comment by siddharth9820** [comment]
Can you please post the loss curves for a model before and after your changes? If those are identical then this PR should be good to go.

**Comment by taozhiwei** [comment]
@siddharth9820 https://github.com/microsoft/DeepSpeed/actions/runs/9605259289/job/26492504473?pr=5626

**Comment by taozhiwei** [comment]
> Can you please post the loss curves for a model before and after your changes? If those are identical then this PR should be good to go.
How do I put the pictures in? I tried a few times but was unsuccessful.

**Comment by siddharth9820** [comment]
@taozhiwei you can take a screenshot and paste it here. Or maybe you can upload it to a shared gdrive location and share that with us?

**Comment by taozhiwei** [comment]
test
 
test

**Comment by taozhiwei** [comment]
> @taozhiwei you can take a screenshot and paste it here. Or maybe you can upload it to a shared gdrive location and share that with us?

This is the convergence curve, please take a look
[https://imgur.com/Nhj7c1m](url)

**Comment by taozhiwei** [comment]
> @taozhiwei you can take a screenshot and paste it here. Or maybe you can upload it to a shared gdrive location and share that with us?

This is the convergence curve, please take a look.
loss curve.

**Comment by taozhiwei** [comment]
> @taozhiwei you can take a screenshot and paste it here. Or maybe you can upload it to a shared gdrive location and share that with us?

This is the convergence curve, please take a look.
[https://imgur.com/Nhj7c1m](https://imgur.com/Nhj7c1m)

**Comment by taozhiwei** [comment]
[loss curve.](https://imgur.com/y5nDCkT)

**Comment by siddharth9820** [comment]
Thanks for doing this. LGTM

**Comment by tjruwase** [comment]
> Thanks for doing this. LGTM. @tjruwase do we need any other tests?

@taozhiwei, thanks for the PR. This is really a great contribution. 

@siddharth9820, thanks for helping to review. 

Approved.

**Review by tjruwase — APPROVED** [review]

**Comment by siddharth9820** [comment]
@tjruwase or someone else working at Deepspeed might be able to help you eith CI

**Comment by taozhiwei** [comment]
> > @tjruwase or someone else working at Deepspeed might be able to help you with CI
> 
> @taozhiwei, apologies for the delay due to our CI issues. We will merge this asap.

thanks a lot，There are still failed tests this time.[https://github.com/microsoft/DeepSpeed/actions/runs/9728828772/job/26861161513?pr=5626](https://github.com/microsoft/DeepSpeed/actions/runs/9728828772/job/26861161513?pr=5626)
I am unable to reproduce these failed tests locally, CI see detailed logs of failures?

**Comment by taozhiwei** [comment]
> > @tjruwase or someone else working at Deepspeed might be able to help you with CI
> 
> @taozhiwei, apologies for the delay due to our CI issues. We will merge this asap.

The CI  failed again, Please help trigger it again. thanks

**Comment by taozhiwei** [comment]
due http 429 failed again. @tjruwase

**Comment by siddharth9820** [comment]
@tjruwase anyway I can help out with this?

**Comment by tjruwase** [comment]
> @tjruwase anyway I can help out with this?

@siddharth9820, thanks for offering. The problem is due to our flaky CI, and we working to resolve. 

@taozhiwei, thanks for your patience.

**Comment by loadams** [comment]
> > > @tjruwase anyway I can help out with this?
> > 
> > 
> > @siddharth9820, thanks for offering. The problem is due to our flaky CI, and we working to resolve.
> > @taozhiwei, thanks for your patience.
> 
> @tjruwase failed again.

Hi @taozhiwei, we are still working on this, as soon as we can get things running in CI again (infrastructure issues) I'll make sure this PR is merged.

**Comment by loadams** [comment]
> > > > @tjruwase anyway I can help out with this?
> > > 
> > > 
> > > @siddharth9820, thanks for offering. The problem is due to our flaky CI, and we working to resolve.
> > > @taozhiwei, thanks for your patience.
> > 
> > 
> > @tjruwase failed again.
> 
> Hi @taozhiwei, we are still working on this, as soon as we can get things running in CI again (infrastructure issues) I'll make sure this PR is merged.

Tests passed, re-merging develop then this should be merged.  Thanks for your patience, @taozhiwei

**Comment by siddharth9820** [comment]
Lessgo!

**Comment by taozhiwei** [comment]
Thank you very much for your help! @loadams @tjruwase @siddharth9820

**Pull request merged**
