### PR TITLE
ZeRO-Inference refresh

### PR DESCRIPTION
**Pull request by tjruwase**
Two new optimizations
- Weight quantization
- KV cache offloading to CPU memory

### CODE REVIEW

**Comment by delock** [comment]
@tjruwase are there examples using weight quantization and kv_cache offloading?

**Comment by tjruwase** [comment]
> @tjruwase are there examples using weight quantization and kv_cache offloading? Wonder what it takes to support int4 on other accelerators as well.

Sorry, that release won't be ready until next week. It will be great to get your feedback.

**Comment by tjruwase** [comment]
FYI, @donglinz @cli99

**Review by awan-10 — APPROVED** [review]

**Comment by ftian1** [comment]
@tjruwase May I get some inputs from your side about contributing more weight only quantization algorithms like WeightOnly RTN/AWQ/GPTQ to DeepSpeed inference? is it ok for DeepSpeed inference to accept other compression algos except for ZeRO? and some of such algos may require calibration on some datasets which may have impact on inference API. do you think it's valuable to add? or shall we stick on those data-free compression at first?

**Comment by ftian1** [comment]
and some questions/comments about current PR: 
1. will _init_group_wise_weight_quantization() be the final interface exposing to user to enable weight quantization? it's a little weird as its name convention is more like internal function naming and the user experiment is not quite good.

2. will this feature be enabled in DeepSpeed Inference path? that's user can enable this feature by invoking deepspeed.init_inference() but not below

```python
        model = AutoModel.from_pretrained('facebook/opt-125m', torch_dtype=torch.float16)
        model = model.eval()

        model = _init_group_wise_weight_quantization(model, ds_config)
        ds_engine = deepspeed.initialize(model=model, config_params=ds_config)[0]
```

**Comment by tjruwase** [comment]
> and some questions/comments about current PR:
> 
> 1. will _init_group_wise_weight_quantization() be the final interface exposing to user to enable weight quantization? it's a little weird as its name convention is more like internal function naming and the user experiment is not quite good.

`_init_group_wise_weight_quantization()` is still experimental. We hope to finalize the interface soon. 

> 2. will this feature be enabled in DeepSpeed Inference path? that's user can enable this feature by invoking deepspeed.init_inference() but not below
> 
> ```python
>         model = AutoModel.from_pretrained('facebook/opt-125m', torch_dtype=torch.float16)
>         model = model.eval()
> 
>         model = _init_group_wise_weight_quantization(model, ds_config)
>         ds_engine = deepspeed.initialize(model=model, config_params=ds_config)[0]
> ```
> 
Yes, this is the plan. 

> 3. may I know when this PR will be merged? or is there any special concerns on not merging such feature to DeepSpeed?

This week.

**Pull request merged**
