### PR TITLE
Add fp8-fused gemm kernel

### PR DESCRIPTION
**Pull request by sfc-gh-reyazda**
This PR adds the new fused kernel for the Dense GeMM using fp8-quantized weight.

### CODE REVIEW

**Review by HeyangQin — APPROVED** [review]

**Comment by jeffra** [comment]
One thing that needs to be resolved before merging this, this kernel requires `triton==2.3.0`. This should be checked at runtime and communicated to users somehow.

**Comment by HeyangQin** [comment]
Hi @jeffra. To clarify, does this kernel require exactly `triton==2.3` or `triton>=2.3`?

**Comment by jeffra** [comment]
> Hi @jeffra. To clarify, does this kernel require exactly `triton==2.3` or `triton>=2.3`?

@sfc-gh-reyazda would know better, I am not sure if we've tested with newer triton than 2.3.0. I have not personally tested this at least.

**Comment by sfc-gh-reyazda** [comment]
> Hi @jeffra. To clarify, does this kernel require exactly `triton==2.3` or `triton>=2.3`?

It needs that specific version, unfortunately triton keeps changing/improving and their APIs change too so it is hard to track it properly. That's also another motivation to move to cutlass soon and have a more solid implementation to work independent of other libraries. On the other hand, Triton gives the flexibility to run on various hardwares. So, it is always a tradeoff. I think we need to have some more discussions on such dependencies later in a different discussion.
Best,
Reza

**Pull request merged**
