### PR TITLE
feat(activation_checkpointing): add `non_reentrant_checkpoint` to support inputs require no grad

### PR DESCRIPTION
**Pull request by hughpu**
The added function is union of `torch.utils.checkpoint._checkpoint_without_reentrant` and `CheckpointFunction` in `checkpointing` module. 

 * this aim to solve the back probagation error raised from all input requires no grad, such as first layer of normal training, lora training until layer get lora injected, traditional fintune with only last layer trainable, etc... 
 * `_checkpoint_without_reentrant` has already been implemented in pytorch for a while, the solution is stable at most time except for jit script module.
 * can help to solve the issue which is hacked by `deepspeed.runtime.pipe.module.PipelineModule._is_checkpointable`
 * unit test added and proved to work, also tested with pipeline module lora tuning project as `activation_checkpoint_func` without specifing `checkpointable_layers`

### CODE REVIEW

**Comment by hughpu** [comment]
@tjruwase @mrwyattii may I know is there any possibility that this PR can get some suggestion? since it's already pending for 2 weeks without any feedback.
* This PR is implemented in an extension way without any modification to existing code neither features. Just an new option for checkpointing function. Not harmful.
* It's not sth brandy new and actually the re-implementation of Pytorch feature [reentrant-checkpoint](https://github.com/pytorch/pytorch/issues/62654)
* this can help solving the issues as, 1) first stage with embedding cannot be checkpointed. 2) peft-tuning with first stages untrainable cause output tensor requires no grad, lossing grad_fn etc.

**Comment by tjruwase** [comment]
@hughpu, apologies for the delay. We will review asap.

**Review by tohtana — APPROVED** [review]
Thank you @hughpu for this great PR!

**Comment by hughpu** [comment]
@tohtana @tjruwase thank you for the review!

**Comment by hughpu** [comment]
hi @tjruwase, it seems the merging is stopped by some http error raised from huggingface, would you mind to merge it again?

**Comment by hughpu** [comment]
hi @tjruwase , shall we move forward to merge this PR? feel free to let me know if there is anything that I can do to facilitate this.

**Comment by tjruwase** [comment]
@hughpu, apologies for the delay. It is now queued for merging.

**Pull request merged**
