### PR TITLE
Bfloat16 zero2

### PR DESCRIPTION
**Pull request by raamjad**
Enabling support for Bfloat16 with ZeRO-2 optimizer, partially resolving the issue#974
https://github.com/microsoft/DeepSpeed/issues/974

Bfloat16 collective communication requires NCCL 2.10.3.

### CODE REVIEW

**Comment by szhengac** [comment]
@ShadenSmith can you help review this PR?

**Comment by raamjad** [comment]
@tjruwase  Seems like all the tests have successfully passed/skipped. I did notice that I didn't update the skip message based on additional checks I introduced so I will update that. Is there anything else that is needed before merging this PR? Thanks for your help

**Comment by tjruwase** [comment]
> @tjruwase Seems like all the tests have successfully passed/skipped. I did notice that I didn't update the skip message based on additional checks I introduced so I will update that. Is there anything else that is needed before merging this PR? Thanks for your help

@raamjad, thanks for your hard work on this PR. I have approved the changes and was hoping to merge over the weekend until the tests started failing, which you have now fixed. All that is left now for a successful test run, and I will merge.

**Comment by raamjad** [comment]
> > @tjruwase Seems like all the tests have successfully passed/skipped. I did notice that I didn't update the skip message based on additional checks I introduced so I will update that. Is there anything else that is needed before merging this PR? Thanks for your help
> 
> @raamjad, thanks for your hard work on this PR. I have approved the changes and was hoping to merge over the weekend until the tests started failing, which you have now fixed. All that is left now for a successful test run, and I will merge.

Thanks!

**Pull request merged**
