### PR TITLE
Reflect use_parallel_residual in mlp_after_attn for module_inject

### PR DESCRIPTION
**Pull request by twaka**
In transformers, `use_parallel_residual` argument controls the residual computing way of gpt-neox since v4.23.0.
https://github.com/huggingface/transformers/pull/18695

In deepspeed, `mlp_after_attn` controls it but currently it's not aware `use_parallel_residual`.

This PR makes to set `mlp_after_attn` according to `use_parallel_residual` if exists.

### CODE REVIEW

**Comment by loadams** [comment]
Hi @twaka - apologies for not getting to review this sooner - is this a PR that still makes sense to complete?  If so, could you resolve the merge conflicts and we can review and complete this?  I lack permissions to your fork so I'm not able to resolve the conflicts.

**Comment by twaka** [comment]
Thank you for reminding me @loadams 
I have updated the fix based on the latest master.
This is still required to correctly inference models that customizes use_parallel_residual when training.

**Comment by loadams** [comment]
> Thank you for reminding me @loadams I have updated the fix based on the latest master. This is still required to correctly inference models that customizes use_parallel_residual when training.

Hi @twaka - I'm so sorry for losing track of this PR - do you still believe this should be merged?

**Comment by twaka** [comment]
Thanks for notifying. The model I wanted to support is bit outdated so I think it's ok to close.

**Comment by loadams** [comment]
> Thanks for notifying. The model I wanted to support is bit outdated so I think it's ok to close.

@twaka - thanks for the reply, apologies for dropping the ball on this long ago from our side.

**Pull request closed without merging**
