### PR TITLE
[save_16bit_model] add missing prologue

### PR DESCRIPTION
**Pull request by stas00**
Trying to fix https://github.com/microsoft/DeepSpeed/issues/1686

So far at least part of the problem that was identified is that  `save_16bit_model` fails in certain situations, e.g. when `save_interval % grad_accum != 0`

This PR copies the pre-amble from `save_checkpoint` which solves this particular problem

TODO:

- this PR can't be merged until this bug is fixed: https://github.com/microsoft/DeepSpeed/issues/1748
- needs a local test - have a HF Trainer way to reproduce the problem https://github.com/microsoft/DeepSpeed/issues/1686#issuecomment-1026486913

### CODE REVIEW

**Comment by stas00** [comment]
So this PR fixes the situation of incomplete grad accumulation, but the fix itself fails in another case:
```
RUN_SLOW=1 pyt tests/deepspeed/test_deepspeed.py::TestDeepSpeedWithLauncher::test_load_best_model_1_zero3
[...]
stderr: Traceback (most recent call last):
stderr:   File "/mnt/nvme1/code/huggingface/transformers-master/examples/pytorch/translation/run_translation.py", line 624, in <module>
stderr:     main()
stderr:   File "/mnt/nvme1/code/huggingface/transformers-master/examples/pytorch/translation/run_translation.py", line 542, in main
stderr:     trainer.save_model()  # Saves the tokenizer too for easy upload
stderr:   File "/mnt/nvme1/code/huggingface/transformers-master/src/transformers/trainer.py", line 2081, in save_model
stderr:     if not self.deepspeed.save_fp16_model(output_dir, WEIGHTS_NAME):
stderr:   File "/mnt/nvme1/code/github/00optimize/deepspeed/deepspeed/runtime/engine.py", line 3120, in save_fp16_model
stderr:     return self.save_16bit_model(save_dir, save_filename)
stderr:   File "/mnt/nvme1/code/github/00optimize/deepspeed/deepspeed/runtime/engine.py", line 3146, in save_16bit_model
stderr:     self.optimizer.save_checkpoint_prologue()
stderr:   File "/mnt/nvme1/code/github/00optimize/deepspeed/deepspeed/runtime/zero/stage3.py", line 3134, in save_checkpoint_prologue
stderr:     self._partition_all_parameters()
stderr:   File "/mnt/nvme1/code/github/00optimize/deepspeed/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
stderr:     return func(*args, **kwargs)
stderr:   File "/mnt/nvme1/code/github/00optimize/deepspeed/deepspeed/runtime/zero/stage3.py", line 2851, in _partition_all_parameters
stderr:     raise RuntimeError(f"{param.ds_summary()} expected to be released")
stderr: RuntimeError: {'id': 5, 'status': 'AVAILABLE', 'numel': 64, 'ds_numel': 64, 'shape': (32, 2), 'ds_shape': (32, 2), 'requires_grad': True, 'grad_shape': None, 'persist': True, 'active_sub_modules': set()} expected to be released
```

@tjruwase, any idea what might be happening here? So it's the added `save_checkpoint_prologue` that breaks.

**Comment by stas00** [comment]
I am pretty sure that the problem lies in the fact that this test `test_load_best_model_1_zero3` does `deepspeed.load_checkpoint` **after** deepspeed did some forwards already. We have run into this issue multiple times already. To remind currently this works:

 ```
 deepspeed.load_checkpoint()
 train()
 deepspeed.save_checkpoint()
 ```
 
 but this breaks:
 
 ```
 deepspeed.load_checkpoint()
 train()
 deepspeed.save_checkpoint()
 deepspeed.load_checkpoint()
 train()
 ```

Deepspeed can't handle the latter scenario and breaks.

So the workaround we found was to re-init deepspeed engine from scratch:
https://github.com/huggingface/transformers/blob/21dcaec5d5d63b77a6132f132d25e65a10d5d457/src/transformers/trainer.py#L1520-L1530

but somehow with this PR's change it breaks too.

**Comment by stas00** [comment]
I think I may have found the culprit to the failing test reported in https://github.com/microsoft/DeepSpeed/pull/1741#issuecomment-1028627167

I reduced it to a simple:

```
deepspeed.load_checkpoint()
# no train in between:
deepspeed.save_checkpoint()
```

it fails with same error as in https://github.com/microsoft/DeepSpeed/pull/1741#issuecomment-1028627167

@tjruwase, any suggestions here? 

I will try to write a test meanwhile

**Comment by tjruwase** [comment]
@stas00, is this still in draft mode or ready for review?

**Comment by stas00** [comment]
and https://github.com/microsoft/DeepSpeed/pull/1750 fixes this test when used with this PR:
```
RUN_SLOW=1 pytest tests/deepspeed/test_deepspeed.py::TestDeepSpeedWithLauncher::test_load_best_model_1_zero3
```

This manual test now passes with the current PR:
```
USE_TF=0 deepspeed --num_gpus 2 examples/pytorch/translation/run_translation.py \
--model_name_or_path t5-small --output_dir /tmp/zero3 --overwrite_output_dir \
--max_train_samples 10 --max_eval_samples 10 --max_source_length 128 \
--max_target_length 128 --val_max_target_length 128 --do_train --do_eval \
--num_train_epochs 1 --per_device_train_batch_size 4 \
--per_device_eval_batch_size 4 --learning_rate 3e-3 --warmup_steps 500 \
--predict_with_generate --eval_steps 1 --group_by_length \
--dataset_name wmt16 --dataset_config ro-en --source_lang en --target_lang ro \
--source_prefix 'translate English to Romanian: ' --deepspeed \
tests/deepspeed/ds_config_zero3.json \
--save_steps 1 --gradient_accumulation_steps 3
```

So the only remaining thing is to write a deepspeed test that does the above.

**Comment by stas00** [comment]
ok, added test, reproducing https://github.com/microsoft/DeepSpeed/issues/1686 and this PR fixes it.

This is good to go once CI completes.

**Comment by stas00** [comment]
The CI failures are not related to this PR I think.

**Comment by stas00** [comment]
@tjruwase, this should be good to merge. Not sure if you want to re-run the CI.

**Comment by tjruwase** [comment]
Overriding flaky unit tests.

**Pull request merged**
