### PR TITLE
Fix pipline dataloader when batch elements contain tuple

### PR DESCRIPTION
**Pull request by ghosthamlet**

### CODE REVIEW

**Review by jeffra — APPROVED** [review]
lgtm, /cc @ShadenSmith for another check though

**Review by ShadenSmith — APPROVED** [review]

**Comment by ShadenSmith** [comment]
lgtm!

**Comment by ghosthamlet** [comment]
Hi @jeffra, merge failed for test_pipe.py line 246, in _helper:
```
    assert rel_diff(base_avg, test_avg) < 0.03
AssertionError: assert 0.03816467364302331 < 0.03
 +  where 0.03816467364302331 = rel_diff(1.8875272107124328, 1.8154903507232667)
```
 what can I do about it? it seems like not related to my simple commit.

**Comment by jeffra** [comment]
> Hi @jeffra, merge failed for test_pipe.py line 246, in _helper:
> 
> ```
>     assert rel_diff(base_avg, test_avg) < 0.03
> AssertionError: assert 0.03816467364302331 < 0.03
>  +  where 0.03816467364302331 = rel_diff(1.8875272107124328, 1.8154903507232667)
> ```
> 
> what can I do about it? it seems like not related to my simple commit.

Yeah, this is pretty strange actually. I was just talking with @ShadenSmith about this as well. We need to investigate further since this shouldn't have anything to do with your PR changes.

**Comment by ghosthamlet** [comment]
Ok, thanks.

**Review by raghavthind2005 — APPROVED** [review]

**Comment by rocm-mici** [comment]
Can one of the admins verify this patch?

**Pull request merged**
