### PR TITLE
Fix wrong documentation of `ignore_unused_parameters`

### PR DESCRIPTION
**Pull request by UniverseFly**
The documentation says:

> `ignore_unused_parameters: bool = True`
> ...
> This is set to `False` **(which should be `True`)** by default, which means unused parameters are ignored and training continues.

Hence the inconsistency.

### CODE REVIEW

**Review by tjruwase — APPROVED** [review]

**Comment by UniverseFly** [comment]
Hi @tjruwase, the original commit encountered some unexpected unit test errors even if it only modified the docstring. Could you kindly check if there's anything wrong? Thanks.

**Comment by loadams** [comment]
> Hi @tjruwase, the original commit encountered some unexpected unit test errors even if it only modified the docstring. Could you kindly check if there's anything wrong? Thanks.

Hi @UniverseFly - there is a known CI issues we are working on.  There doesn't appear to be anything wrong with your PR, we will get it merged shortly, thanks!

**Review by tjruwase — APPROVED** [review]

**Comment by keunwoochoi** [comment]
i think we still see the inconsistent documentation on this..

**Comment by loadams** [comment]
Hi @keunwoochoi - could you link the inconsistent docs?  We'd certainly like to fix them if there is anything inconsistent

**Comment by loadams** [comment]
@keunwoochoi - the docs inconsistency should be fixed here: https://github.com/microsoft/DeepSpeed/pull/4949

Link to the code where the default is set: https://github.com/microsoft/DeepSpeed/blob/13d84b4912492d40b68f4da7bc570e47b54bce2a/deepspeed/runtime/zero/config.py#L242C4-L242C42

**Comment by keunwoochoi** [comment]
@loadams thanks!

**Pull request merged**
