### PR TITLE
Handle when `backend` is also in compile_kwargs

### PR DESCRIPTION
**Pull request by oraluben**
cc @tohtana

### CODE REVIEW

**Comment by tohtana** [comment]
Hi @oraluben, Can you elaborate your goal with this PR?

**Comment by tohtana** [comment]
Hi @oraluben,
Thank you for the clarification. It makes sense. At this point, it's not very clear how we benefit from treating backend separately from other compiler options, but we want to keep the option for compatibility.

I agree with the fix, but the method for merging dictionaries is not correct, as the tests have failed. Could you address this?
It would also be good if we could show a warning when backend is specified in both ways and one of them is overwritten.

**Comment by oraluben** [comment]
Is there anything wrong with the CI? My PRs keep timeout in v100.

**Comment by loadams** [comment]
> Is there anything wrong with the CI? My PRs keep timeout in v100.

Yes this looks to be an issue on our side, I will take care of this.

**Review by tohtana — APPROVED** [review]

**Pull request merged**
