### PR TITLE
checking process_group before merging bucket ranges (#3521)

### LINKED ISSUE #3521: [BUG] average_tensor coalesing does not take process_group into consideration for MoE
**Describe the bug**
When decision about coalescing adjacent tensors is made right now it is currently only based on `partition_id` [here](https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/runtime/zero/stage_1_and_2.py#L923) which is simply target's rank in the `range(dist.get_world_size(group=process_group))`. This means that even though expert data parallel and data parallel both have `partition_id=0` they could belong to different physical ranks in different `process_group`s.

**To Reproduce**
A unit test will be added soon.

**Expected behavior**
`stage_1_and_2`'s `average_tensor` should detect `param_group`s belong to different `process_group`s, e.g. by remembering `prev_process_group`.

**ds_report output**
```
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-devel package with yum
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  using untested triton version (2.0.0), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
utils .................. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/home/azzhipa/.local/lib/python3.9/site-packages/torch']
torch version .................... 1.13.1+cu116
deepspeed install path ........... ['/home/azzhipa/workspace/DeepSpeed/deepspeed']
deepspeed info ................... 0.9.2+f7d71ec1, f7d71ec1, HEAD
torch cuda version ............... 11.6
torch hip version ................ None
nvcc version ..................... 11.6
deepspeed wheel compiled w. ...... torch 1.12, cuda 11.6
```

**Screenshots**
N/A

**System info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - GPU count and types: 1 machine with 8x A100s
 - Interconnects (if applicable) 4x 100 Gbps AWS EFA adaptors
 - Python version: 3.9
 - Any other relevant info about your setup: N/A

**Launcher context**
Launching with `deepspeed` runner

**Docker context**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by clumsy**
Recreating previous pull request: https://github.com/microsoft/DeepSpeed/pull/3522

Fixed #3521

### CODE REVIEW

**Comment by clumsy** [comment]
@tjruwase Here's the new PR so the same patch as before, sorry again.

**Review by tjruwase — APPROVED** [review]

**Comment by tjruwase** [comment]
@clumsy, thanks for recreating the PR. It is greatly appreciated contribution.

**Comment by clumsy** [comment]
Please let me know if more work is required for this change to get merge, @tjruwase .

**Comment by tjruwase** [comment]
> Please let me know if more work is required for this change to get merge, @tjruwase .

Sorry, this dropped from my mind. No more work required. I have set auto-merge once CI completes. Thanks for the reminder.

**Comment by clumsy** [comment]
Hi @tjruwase, looks like seemingly unrelated `TestHybridEngineTextGen` test keeps failing. Is this the reason why this change cannot be merged?

**Comment by tjruwase** [comment]
> Hi @tjruwase, looks like seemingly unrelated `TestHybridEngineTextGen` test keeps failing. Is this the reason why this change cannot be merged?

This test failure is preventing the the auto-merge. But I don't think the test is related to your changes, so I have restarted the CI. Let's see what happens this time.

**Comment by clumsy** [comment]
@tjruwase there's some weird CUDA OOM going on, where a test (`TestCompression.test_conv1d_convertion`) I didn't even affect with my changes fails. Is the testing instance being shared by multiple CI workflows?

**Comment by clumsy** [comment]
Reducing micro batch size to try and avoid OOM. Please let me know if there's any concern with this, @tjruwase Just trying to get this fix merged.

**Comment by clumsy** [comment]
Still no luck, @tjruwase . Is there a known issue with CUDA OOM in DeepSpeed tests?
I only added a few layers to SimpleMoEModel that is not that widely used, yet unrelated test fail too.
Do test parameters need any tuning?

**Comment by tjruwase** [comment]
> Still no luck, @tjruwase . Is there a known issue with CUDA OOM in DeepSpeed tests? I only added a few layers to SimpleMoEModel that is not that widely used, yet unrelated test fail too. Do test parameters need any tuning?

Apologies, CI seem quite unstable lately. We are taking a closer look.

**Pull request merged**
