### PR TITLE
Graceful exit on failures for multi-node runs

### PR DESCRIPTION
**Pull request by jerrymannil**
* Use Popen.terminate() to stop the child processes gracefully; Kill them if terminate doesn't work

* The Popen.kill() command cause the training processes to end abruptly. This may cause the child processes to become zombies without communicating properly to the parent process about the kill signal. So the ssh session continue to wait for signals from the child processes, causing it to not return back to the pdsh command

Fixes microsoft#1995

### CODE REVIEW

**Comment by jerrymannil** [comment]
@jeffra can you look at this ?

**Comment by jerrymannil** [comment]
@jeffra @tjruwase Can one of you help with merging ?

**Comment by jerrymannil** [comment]
@jeffra @tjruwase  Can one of you help with merging ?

**Comment by tjruwase** [comment]
@jerrymannil, taking a look. Apologies for the delay.

**Review by tjruwase — APPROVED** [review]

**Review by jeffra — APPROVED** [review]
Thank you @jerrymannil , so sorry for the delay.

**Pull request merged**
