### PR TITLE
Render docs for pipe.ProcessTopology

### PR DESCRIPTION
**Pull request by jamesr66a**
I was reading through the pipeline parallelism docs and noticed the `topology` parameter for the [PipelineModule](https://deepspeed.readthedocs.io/en/latest/pipeline.html#model-specification) class referenced `deepspeed.pipe.ProcessTopology`. This doesn't seem to actually exist (i.e. it's not imported in pipe/__init__.py), but it does exist in `deepspeed.runtime.pipe`.

This patch adds autoclass docs for `ProcessToplogy` to the pipeline parallelism docs and updates the reference in the `PipelineModule` docstring to reference that. Alternatively, `ProcessTopology` could be imported in `pipe/__init__.py`.

### CODE REVIEW

**Review by tjruwase — APPROVED** [review]

**Comment by tjruwase** [comment]
@jamesr66a, thanks for the PR.

**Comment by jamesr66a** [comment]
FYI I am working through getting the necessary CLA approvals with Legal on our end; may take a little while

**Review by tjruwase — APPROVED** [review]

**Comment by jeffra** [comment]
> FYI I am working through getting the necessary CLA approvals with Legal on our end; may take a little while

With Microsoft at least we have a process of approval for involved external contributions, however for small doc changes like this there is often no approval required. Not sure the policy for you though :)

**Comment by jamesr66a** [comment]
CLA signed, should be good to go

**Pull request merged**
