### PR TITLE
Fix: Sparse tensors not updating

### PR DESCRIPTION
**Pull request by Dipet**
`param.grad.data` returns new object, for this reason we do not assign updated sparse gradients to the target tensor and the optimizer works with unique gradient tensor on each device.

### CODE REVIEW

**Comment by tjruwase** [comment]
@Dipet, thanks for sharing this context. I have not worked a lot with sparse tensors, so that is probably why I have not run into this issue. My suggestion would be to implement this logic only for the sparse tensor code path, so that the dense tensor code paths remain unchanged for backwards-compatibility. I am happy to help brain-storm on this. 

FYI @jeffra, who has worked more on sparse tensors.

**Comment by Dipet** [comment]
@jeffra Tests failed, but it looks like problem with hardware, because tests failed on `nvcc` call.

**Comment by Dipet** [comment]
@jeffra Can you look at the PR?

**Comment by Dipet** [comment]
Guys, could you take a look at this PR?

**Comment by tjruwase** [comment]
@Dipet, apologies for the delay. I had suggested restricting this change only to sparse tensors so that dense tensor code paths remain backwards compatible. Is there a problem with doing that?

**Comment by Dipet** [comment]
@tjruwase I changed the logic for sparse tensors only, dense tensors should work the same as before.

**Review by tjruwase — APPROVED** [review]
Thanks!

**Pull request merged**
