### PR TITLE
Revise param_shapes to be a list of ordered dict

### PR DESCRIPTION
**Pull request by eelxpeng**
Resoving the issue https://github.com/microsoft/DeepSpeed/issues/1412 . It revises the param_shapes to be a list of ordered dict to take into account of param group. Also revises the `zero_to_fp32.py` to accomodate the change of zero2. But have not tested with zero3. @stas00

### CODE REVIEW

**Comment by stas00** [comment]
Amazing work, @eelxpeng!

Could you please give @stas00 a temp write access to your fork of deepspeed, so that I could work on adjusting z3 and adding new tests?

Otherwise I can't push into this PR as I have no write access to deepspeed.

Thank you!

**Comment by eelxpeng** [comment]
I should have allowed the edits by maintainers. Let me know if it doesn't work.
image

**Comment by stas00** [comment]
I'm not a maintainer. I'm not part of Deepspeed.

**Comment by eelxpeng** [comment]
@stas00 Just added you as collaborator to my fork. Tried several times before but seems some bug with github and failed previously. Now it works.

**Comment by stas00** [comment]
Awesome, thank you - I hope to have time to work on this afternoon.

**Comment by tjruwase** [comment]
@eelxpeng, thanks for this PR. Can you please address the conflict?

**Comment by stas00** [comment]
@tjruwase, I'm on top of this one.

This is fixing z2+multiple param groups - needs tests and fixing up z3.

**Comment by stas00** [comment]
OK, so what I pushed in:
1. a set of z2/z3 tests with 2 param groups - probably could refactor some of it down the road
2. I split `_get_fp32_state_dict_from_zero_checkpoint` into 2 separate functions for z2 and z3 as they are starting to diverge too much. I then flattened `param_shapes` to how it was in the original code for z3, which allowed me to keep the old z3 code mostly unmodified. 

All the new zero2 code is by @eelxpeng - basically replicating the logic from the `zero2.py` which is probably much smarter than me trying to re-invent the wheel.

Much appreciating your work @eelxpeng, For some reason I still have a hard time grasping some of that partitioning code and so your contribution was very timely.

**Comment by stas00** [comment]
@tjruwase, this PR is most likely should close https://github.com/microsoft/DeepSpeed/issues/1317
once the 2 users confirm that it indeed resolves their 2 distinct issues.

I can't edit OP, so perhaps you or @eelxpeng could add to it:
```
Fixes: https://github.com/microsoft/DeepSpeed/issues/1317
Fixes: https://github.com/microsoft/DeepSpeed/issues/1412
```

**Comment by tjruwase** [comment]
Thanks @stas00. I will also review and track further updates.

**Comment by stas00** [comment]
Any idea why Formatting job fails?

I get no diff after running `pre-commit run --all-files`

**Comment by stas00** [comment]
Ah, you have an issue with pytorch version - it's not a PR issue:

```
 Could not find a version that satisfies the requirement torch==1.9.0+cpu 
 ```

**Comment by stas00** [comment]
@eelxpeng, could you please sign the CLA so that your PR could be merged?

See https://github.com/microsoft/DeepSpeed/pull/1424#issuecomment-932443012

Thank you!

**Comment by eelxpeng** [comment]
@stas00 Done. Thanks for the follow-up commits. Appreciate your help and driving this.

**Review by tjruwase — APPROVED** [review]

**Comment by stas00** [comment]
Thanks for merting, @tjruwase 

It doesn't look like OP was updated with the suggested:
https://github.com/microsoft/DeepSpeed/pull/1424#issuecomment-932668082

So the open Issues that this PR should have closed remain open.

https://github.com/microsoft/DeepSpeed/issues/1412
https://github.com/microsoft/DeepSpeed/issues/1317

**Comment by tjruwase** [comment]
@stas00, thanks for the heads up. I have manually closed #1317 and #1412.

**Pull request merged**
