### PR TITLE
fix comms dtype

### PR DESCRIPTION
**Pull request by mayank31398**
is the comms dtype name a bug?
can we fix it?

### CODE REVIEW

**Comment by mayank31398** [comment]
@tjruwase @mrwyattii 
can we fix this?
its pretty weird and confusing to have bf16 for grad_accum_dtype etc but `bfp16` for comms dtype.

**Review by tjruwase — APPROVED** [review]

**Comment by tjruwase** [comment]
@mayank31398, thanks! Yes, this was confusing.

**Comment by mayank31398** [comment]
@tjruwase the tests still haven't run yet 😆

**Comment by tjruwase** [comment]
> @tjruwase the tests still haven't run yet 😆
It seems our CI is broken, again :(. Will fix asap.

**Comment by mayank31398** [comment]
@tjruwase any updates on this?

**Comment by loadams** [comment]
> @tjruwase any updates on this?

We are still working on fixing the CI issues.  The tests should automatically resume running when this is fixed and we will make sure to get this merged then.  Sorry for the delay.

**Comment by loadams** [comment]
> > @tjruwase any updates on this?
> 
> @mayank31398 - We are still working on fixing the CI issues. The tests should automatically resume running when this is fixed and we will make sure to get this merged then. Sorry for the delay.

@mayank31398 - this should be resolved now, we are waiting on the runners to come back, and the backlog should start to clear.  Sorry about that.

**Comment by mayank31398** [comment]
@loadams no worries
Thanks for reviewing 😃

**Pull request merged**
